# Fuego contra Fuego

Instalamos, cargamos y seteamos el entorno

In [42]:
%pip install optuna

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: optuna in /Users/manuelmarasco/Library/Python/3.9/lib/python/site-packages (4.9.0)
Requirement already satisfied: alembic>=1.5.0 in /Users/manuelmarasco/Library/Python/3.9/lib/python/site-packages (from optuna) (1.16.5)
Requirement already satisfied: colorlog in /Users/manuelmarasco/Library/Python/3.9/lib/python/site-packages (from optuna) (6.12.0)
Requirement already satisfied: numpy in /Users/manuelmarasco/Library/Python/3.9/lib/python/site-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /Users/manuelmarasco/Library/Python/3.9/lib/python/site-packages (from optuna) (26.3)
Requirement already satisfied: sqlalchemy>=1.4.2 in /Users/manuelmarasco/Library/Python/3.9/lib/python/site-packages (from optuna) (2.0.52)
Requirement already satisfied: tqdm in /Users/manuelmarasco/Library/Python/3.9/lib/python/site-packages (from optuna) (4.70.0)
Requirement already satisfied: PyYAML in /Users/manuelmarasco/Library/Python/3.9/lib/python/site-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /Users/manuelmarasco/Library/Python/3.9/lib/python/site-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in /Users/manuelmarasco/Library/Python/3.9/lib/python/site-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: tomli in /Users/manuelmarasco/Library/Python/3.9/lib/python/site-packages (from alembic>=1.5.0->optuna) (2.4.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /Users/manuelmarasco/Library/Python/3.9/lib/python/site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [43]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from tqdm.notebook import tqdm

from sklearn.tree import DecisionTreeClassifier, plot_tree,  _tree
from sklearn.model_selection import train_test_split
from sklearn.model_selection import ShuffleSplit, StratifiedShuffleSplit
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer

from joblib import Parallel, delayed

import optuna
from optuna.visualization import plot_optimization_history, plot_param_importances, plot_slice, plot_contour

from time import time

import pickle

In [44]:
base_path = '/Users/manuelmarasco/Library/CloudStorage/GoogleDrive-hola@manuelmarasco.com/Mi unidad/DMEyF/2026/notebooks/'
dataset_path = base_path + 'data/'
modelos_path = base_path + 'modelos/'
db_path = base_path + 'data/'
dataset_file = 'competencia_01.csv'

ganancia_acierto = 1_072_500
costo_estimulo = 27_500

mes_train = 202103
mes_test = 202105

# agregue sus semillas
semilla = 17
semillas = np.random.choice(1000000, size=50, replace=False).tolist()

data = pd.read_csv(dataset_path + dataset_file)

/var/folders/xn/fmllb0ws2fbdtxppprq7r2l00000gn/T/ipykernel_12732/2551575851.py:17: DtypeWarning: Columns (155) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(dataset_path + dataset_file)

Seguimos trabajando con Marzo como entrenamiento y Mayo como test.

In [45]:
X = data[data['foto_mes'] == mes_train]
y = X['clase_ternaria']
X = X.drop(columns=['clase_ternaria'])

In [46]:
X_futuro = data[data['foto_mes'] == mes_test]
y_futuro = X_futuro['clase_ternaria']
X_futuro = X_futuro.drop(columns=['clase_ternaria'])

Y variaremos la forma de la función de ganancia, para poder ser utilizada de una forma más genérica.

In [47]:
def ganancia_prob(y_hat, y, prop=1, class_index=1, threshold=0.025):
  @np.vectorize
  def ganancia_row(predicted, actual, threshold=0.025):
    return  (predicted >= threshold) * (ganancia_acierto if actual == "BAJA+2" else -costo_estimulo)

  return ganancia_row(y_hat[:,class_index], y).sum() / prop

Entrenemos y recordemos cuanto nos daba la ganancia en **Mayo**

Hablemos de ensemables, qué son?

* Un ensemble de modelos es una técnica donde se combinan múltiples modelos individuales para mejorar la precisión y robustez de las predicciones. La idea es que al combinar varios modelos, se pueden aprovechar las fortalezas de cada uno y reducir la posibilidad de errores que podría cometer un único modelo.

**Tipos de ensemble**:
 * **Bagging (Bootstrap Aggregating)**: Consiste en entrenar varios modelos base en diferentes subconjuntos del conjunto de datos de entrenamiento obtenidos mediante técnicas de remuestreo como el bootstrap y luego promediar sus predicciones. Ejemplo: **Random Forest**
 * **Boosting**: En esta técnica, los modelos se entrenan de manera secuencial. Cada modelo intenta corregir los errores cometidos por el modelo anterior. Ejemplo: AdaBoost y **Gradient Boosting**.
 * **Stacking**: En el stacking, se entrenan varios modelos y se combinan usando un "modelo meta". Las predicciones de los modelos base sirven como features para entrenar este modelo meta, que produce la predicción final.

* **Ventajas de usar ensemble de modelos**:
 * **Mejor rendimiento**: Al combinar modelos, generalmente se mejora la precisión en comparación con un solo modelo.
 * **Robustez**: Al integrar diferentes modelos, se mitiga el riesgo de que los errores de un modelo individual afecten gravemente la predicción final.

Pongamos foco en el **Random Forest**

Es un algoritmo de aprendizaje automático que funciona creando un conjunto de árboles de decisión. Para la creación de **árboles distintos** utiliza una técnica llamada bagging para crear múltiples subconjuntos del conjunto de datos de entrenamiento. Cada subconjunto se genera seleccionando al azar muestras del conjunto de datos original con reemplazo. No usa la totalidad de los datos de entrenamiento para cada conjunto. Los datos que quedan fueran son conocidos como **Out of Bag (oob)**

Para cada subconjunto, se construye un árbol de decisión. Sin embargo en cada nodo del árbol, **Random Forest** selecciona de forma aleatoria un grupo de variables y ajusta el árbol con esas variables. Este proceso ayuda a crear árboles que son menos correlacionados entre sí.

Cada árbol en el bosque se entrena de manera independiente usando su respectivo subconjunto de datos. Lueago, para una nueva observación, cada árbol realiza una predicción. El Random Forest luego combina las predicciones de todos los árboles para hacer una predicción final, devolviendo el promedio de las probabilidades de cada árbol individual.

Como desde la clase pasada solo personas más inteligentes, no vamos a empezar a probar **Random Forest** simples. Vamos a parametrizarlo desde el vamos.

Primero vamos a entender algunas limitaciones de la implementación:

El **Random Forest** no soporta nulos! Shame on you sklearn!.

Vamos a tener que imputar los datos. Discutamos entre todos forma de imputar los datos, mientras para salir del paso usamos la peor de todas.

In [48]:
imp_median = SimpleImputer(missing_values=np.nan, strategy='median')
Xi = imp_median.fit_transform(X)
Xif = imp_median.fit_transform(X_futuro)

Los parámetros que se pueden ajustar en el **rf** son

1. **n_estimators**: Número de árboles en el bosque.
2. **max_depth**: Profundidad máxima de los árboles.
3. **min_samples_split**: Número mínimo de muestras requeridas para dividir un nodo interno.
4. **min_samples_leaf**: Número mínimo de muestras requeridas para estar en un nodo hoja.
5. **max_features**: Número de features a usar en cada árbol. **sqrt** es una elección histórica.
6. **max_leaf_nodes**: Número máximo de nodos hoja en cada árbol.
7. **oob_score**: Indica si se usa la muestra fuera de bolsa (out-of-bag) para estimar la calidad del modelo. Para evitar hacer un **montecarlo-cross-validation** que se toma su tiempo, usaremos esta opción para buscar el mejor modelo. No es la mejor opción. Pero no es tan mala.
8. **n_jobs**: Siempre -1, para que use todos los cores presentes en 9. **max_samples**: Fracción de los samples.

Finalmente nuestra función de optimización queda la siguiente forma:

In [ ]:
# def objective(trial):
#     max_depth = trial.suggest_int('max_depth', 2, 32)
#     min_samples_split = trial.suggest_int('min_samples_split', 2, 2000)
#     min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 200)
#     max_features = trial.suggest_float('max_features', 0.05, 0.7)

#     model = RandomForestClassifier(
#         n_estimators=100,
#         max_depth=max_depth,
#         min_samples_split=min_samples_split,
#         min_samples_leaf=min_samples_leaf,
#         max_features=max_features,
#         max_samples=0.7,
#         random_state=semillas[0],
#         n_jobs=-1,
#         oob_score=True
#     )

#     model.fit(Xi, y)

#     return ganancia_prob(model.oob_decision_function_, y)

# storage_name = "sqlite:///" + db_path + "optimization_rf.db"
# study_name = "exp_401_random-forest-opt"

# study = optuna.create_study(
#     direction="maximize",
#     study_name=study_name,
#     storage=storage_name,
#     load_if_exists=True,
# )

[I 2026-09-07 14:20:12,244] Using an existing study with name 'exp_401_random-forest-opt' instead of creating a new one.

In [52]:
study.optimize(objective, n_trials=100)

[I 2026-09-07 14:20:48,032] Trial 243 finished with value: 346307500.0 and parameters: {'max_depth': 17, 'min_samples_split': 395, 'min_samples_leaf': 53, 'max_features': 0.6554986965330545}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:21:17,892] Trial 244 finished with value: 330522500.0 and parameters: {'max_depth': 17, 'min_samples_split': 382, 'min_samples_leaf': 52, 'max_features': 0.6571358876168024}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:21:50,505] Trial 245 finished with value: 347132500.0 and parameters: {'max_depth': 17, 'min_samples_split': 365, 'min_samples_leaf': 51, 'max_features': 0.6466681857048291}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:22:21,211] Trial 246 finished with value: 344575000.0 and parameters: {'max_depth': 17, 'min_samples_split': 461, 'min_samples_leaf': 51, 'max_features': 0.644150529321394}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:22:49,561] Trial 247 finished with value: 340697500.0 and parameters: {'max_depth': 17, 'min_samples_split': 374, 'min_samples_leaf': 59, 'max_features': 0.630959678930349}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:23:20,953] Trial 248 finished with value: 338690000.0 and parameters: {'max_depth': 17, 'min_samples_split': 340, 'min_samples_leaf': 48, 'max_features': 0.660057602515712}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:23:50,209] Trial 249 finished with value: 341137500.0 and parameters: {'max_depth': 16, 'min_samples_split': 377, 'min_samples_leaf': 54, 'max_features': 0.6462689927765186}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:24:18,122] Trial 250 finished with value: 339762500.0 and parameters: {'max_depth': 16, 'min_samples_split': 360, 'min_samples_leaf': 47, 'max_features': 0.637024138857852}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:24:45,828] Trial 251 finished with value: 338222500.0 and parameters: {'max_depth': 18, 'min_samples_split': 415, 'min_samples_leaf': 59, 'max_features': 0.6211273889365001}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:25:11,526] Trial 252 finished with value: 347050000.0 and parameters: {'max_depth': 15, 'min_samples_split': 508, 'min_samples_leaf': 52, 'max_features': 0.6564925199224013}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:25:37,742] Trial 253 finished with value: 349415000.0 and parameters: {'max_depth': 15, 'min_samples_split': 550, 'min_samples_leaf': 57, 'max_features': 0.6509025074268655}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:26:03,688] Trial 254 finished with value: 335225000.0 and parameters: {'max_depth': 15, 'min_samples_split': 606, 'min_samples_leaf': 65, 'max_features': 0.672883538815063}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:26:30,000] Trial 255 finished with value: 335802500.0 and parameters: {'max_depth': 15, 'min_samples_split': 545, 'min_samples_leaf': 58, 'max_features': 0.6661521180858575}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:26:56,018] Trial 256 finished with value: 342622500.0 and parameters: {'max_depth': 15, 'min_samples_split': 478, 'min_samples_leaf': 42, 'max_features': 0.6504541386422438}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:27:21,031] Trial 257 finished with value: 338360000.0 and parameters: {'max_depth': 16, 'min_samples_split': 679, 'min_samples_leaf': 56, 'max_features': 0.6111418491843892}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:27:47,190] Trial 258 finished with value: 334895000.0 and parameters: {'max_depth': 14, 'min_samples_split': 494, 'min_samples_leaf': 49, 'max_features': 0.6409985157706646}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:28:15,745] Trial 259 finished with value: 339102500.0 and parameters: {'max_depth': 15, 'min_samples_split': 514, 'min_samples_leaf': 45, 'max_features': 0.6258166994018503}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:28:47,407] Trial 260 finished with value: 319000000.0 and parameters: {'max_depth': 16, 'min_samples_split': 600, 'min_samples_leaf': 9, 'max_features': 0.6641895019813941}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:29:14,098] Trial 261 finished with value: 343970000.0 and parameters: {'max_depth': 15, 'min_samples_split': 526, 'min_samples_leaf': 56, 'max_features': 0.6570352191656398}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:29:37,437] Trial 262 finished with value: 337727500.0 and parameters: {'max_depth': 13, 'min_samples_split': 562, 'min_samples_leaf': 64, 'max_features': 0.6418683714080229}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:30:01,614] Trial 263 finished with value: 339845000.0 and parameters: {'max_depth': 14, 'min_samples_split': 301, 'min_samples_leaf': 51, 'max_features': 0.6267038967381078}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:30:12,355] Trial 264 finished with value: 344575000.0 and parameters: {'max_depth': 16, 'min_samples_split': 114, 'min_samples_leaf': 47, 'max_features': 0.2570151315800312}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:30:37,229] Trial 265 finished with value: 326700000.0 and parameters: {'max_depth': 14, 'min_samples_split': 48, 'min_samples_leaf': 59, 'max_features': 0.6499051948469798}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:31:02,016] Trial 266 finished with value: 339212500.0 and parameters: {'max_depth': 15, 'min_samples_split': 80, 'min_samples_leaf': 54, 'max_features': 0.6079865055047886}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:31:30,669] Trial 267 finished with value: 343612500.0 and parameters: {'max_depth': 15, 'min_samples_split': 136, 'min_samples_leaf': 51, 'max_features': 0.6738871317947676}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:31:46,656] Trial 268 finished with value: 333877500.0 and parameters: {'max_depth': 14, 'min_samples_split': 308, 'min_samples_leaf': 42, 'max_features': 0.3842281181300816}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:31:54,667] Trial 269 finished with value: 341605000.0 and parameters: {'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 61, 'max_features': 0.17918917511716986}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:32:11,123] Trial 270 finished with value: 344685000.0 and parameters: {'max_depth': 13, 'min_samples_split': 102, 'min_samples_leaf': 56, 'max_features': 0.43405726391632504}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:32:23,366] Trial 271 finished with value: 344795000.0 and parameters: {'max_depth': 16, 'min_samples_split': 166, 'min_samples_leaf': 121, 'max_features': 0.3119022232175065}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:32:47,684] Trial 272 finished with value: 334235000.0 and parameters: {'max_depth': 14, 'min_samples_split': 43, 'min_samples_leaf': 49, 'max_features': 0.6343830328192203}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:33:10,573] Trial 273 finished with value: 349112500.0 and parameters: {'max_depth': 13, 'min_samples_split': 133, 'min_samples_leaf': 18, 'max_features': 0.597555554941552}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:33:33,348] Trial 274 finished with value: 325242500.0 and parameters: {'max_depth': 13, 'min_samples_split': 77, 'min_samples_leaf': 16, 'max_features': 0.5948317363606398}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:33:54,955] Trial 275 finished with value: 337645000.0 and parameters: {'max_depth': 12, 'min_samples_split': 126, 'min_samples_leaf': 21, 'max_features': 0.6144086292066663}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:34:18,056] Trial 276 finished with value: 334867500.0 and parameters: {'max_depth': 13, 'min_samples_split': 345, 'min_samples_leaf': 16, 'max_features': 0.6206295579095374}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:34:49,026] Trial 277 finished with value: 316772500.0 and parameters: {'max_depth': 18, 'min_samples_split': 666, 'min_samples_leaf': 11, 'max_features': 0.6501102470510698}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:35:08,217] Trial 278 finished with value: 338525000.0 and parameters: {'max_depth': 12, 'min_samples_split': 431, 'min_samples_leaf': 193, 'max_features': 0.6059213496842195}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:35:33,107] Trial 279 finished with value: 334565000.0 and parameters: {'max_depth': 14, 'min_samples_split': 287, 'min_samples_leaf': 62, 'max_features': 0.6351641971370989}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:35:54,731] Trial 280 finished with value: 339790000.0 and parameters: {'max_depth': 13, 'min_samples_split': 62, 'min_samples_leaf': 113, 'max_features': 0.5856101626544844}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:36:14,251] Trial 281 finished with value: 343722500.0 and parameters: {'max_depth': 11, 'min_samples_split': 570, 'min_samples_leaf': 180, 'max_features': 0.6589217182029745}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:36:39,312] Trial 282 finished with value: 324197500.0 and parameters: {'max_depth': 13, 'min_samples_split': 1442, 'min_samples_leaf': 24, 'max_features': 0.6863131163030399}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:37:06,203] Trial 283 finished with value: 340202500.0 and parameters: {'max_depth': 17, 'min_samples_split': 109, 'min_samples_leaf': 54, 'max_features': 0.6219071750723333}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:37:31,282] Trial 284 finished with value: 329780000.0 and parameters: {'max_depth': 16, 'min_samples_split': 148, 'min_samples_leaf': 33, 'max_features': 0.5961335204019103}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:37:50,500] Trial 285 finished with value: 329312500.0 and parameters: {'max_depth': 15, 'min_samples_split': 33, 'min_samples_leaf': 19, 'max_features': 0.4479779406423293}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:38:14,437] Trial 286 finished with value: 330880000.0 and parameters: {'max_depth': 14, 'min_samples_split': 879, 'min_samples_leaf': 67, 'max_features': 0.6396606216014884}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:38:33,152] Trial 287 finished with value: 338552500.0 and parameters: {'max_depth': 27, 'min_samples_split': 204, 'min_samples_leaf': 57, 'max_features': 0.42552905261922636}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:38:57,145] Trial 288 finished with value: 339955000.0 and parameters: {'max_depth': 13, 'min_samples_split': 91, 'min_samples_leaf': 51, 'max_features': 0.6692172698424378}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:39:17,017] Trial 289 finished with value: 333437500.0 and parameters: {'max_depth': 10, 'min_samples_split': 260, 'min_samples_leaf': 60, 'max_features': 0.647926266417471}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:39:34,470] Trial 290 finished with value: 339927500.0 and parameters: {'max_depth': 16, 'min_samples_split': 325, 'min_samples_leaf': 39, 'max_features': 0.41585081097975196}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:39:55,005] Trial 291 finished with value: 336985000.0 and parameters: {'max_depth': 12, 'min_samples_split': 1086, 'min_samples_leaf': 53, 'max_features': 0.6283079212704249}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:40:21,116] Trial 292 finished with value: 296367500.0 and parameters: {'max_depth': 15, 'min_samples_split': 141, 'min_samples_leaf': 4, 'max_features': 0.571718996341921}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:40:44,443] Trial 293 finished with value: 343640000.0 and parameters: {'max_depth': 14, 'min_samples_split': 462, 'min_samples_leaf': 44, 'max_features': 0.6117642023804611}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:41:12,768] Trial 294 finished with value: 343337500.0 and parameters: {'max_depth': 17, 'min_samples_split': 33, 'min_samples_leaf': 98, 'max_features': 0.6584284329472663}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:41:31,359] Trial 295 finished with value: 334345000.0 and parameters: {'max_depth': 14, 'min_samples_split': 175, 'min_samples_leaf': 57, 'max_features': 0.471942791565179}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:41:53,748] Trial 296 finished with value: 339625000.0 and parameters: {'max_depth': 12, 'min_samples_split': 222, 'min_samples_leaf': 48, 'max_features': 0.6431620762570895}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:42:18,167] Trial 297 finished with value: 336407500.0 and parameters: {'max_depth': 15, 'min_samples_split': 82, 'min_samples_leaf': 64, 'max_features': 0.6274069714311832}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:42:26,340] Trial 298 finished with value: 339542500.0 and parameters: {'max_depth': 13, 'min_samples_split': 281, 'min_samples_leaf': 105, 'max_features': 0.21779143789061925}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:42:36,620] Trial 299 finished with value: 338387500.0 and parameters: {'max_depth': 9, 'min_samples_split': 118, 'min_samples_leaf': 173, 'max_features': 0.37320020941674276}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:42:54,849] Trial 300 finished with value: 341192500.0 and parameters: {'max_depth': 16, 'min_samples_split': 4, 'min_samples_leaf': 51, 'max_features': 0.4348353502635975}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:43:20,191] Trial 301 finished with value: 340257500.0 and parameters: {'max_depth': 18, 'min_samples_split': 411, 'min_samples_leaf': 70, 'max_features': 0.5999193009075396}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:43:37,994] Trial 302 finished with value: 348672500.0 and parameters: {'max_depth': 26, 'min_samples_split': 183, 'min_samples_leaf': 59, 'max_features': 0.3886760655563583}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:43:53,577] Trial 303 finished with value: 343282500.0 and parameters: {'max_depth': 15, 'min_samples_split': 158, 'min_samples_leaf': 54, 'max_features': 0.3812705773569475}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:44:09,756] Trial 304 finished with value: 338222500.0 and parameters: {'max_depth': 14, 'min_samples_split': 58, 'min_samples_leaf': 46, 'max_features': 0.39775071581928884}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:44:28,083] Trial 305 finished with value: 341055000.0 and parameters: {'max_depth': 17, 'min_samples_split': 187, 'min_samples_leaf': 61, 'max_features': 0.41702161330198817}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:44:42,584] Trial 306 finished with value: 345455000.0 and parameters: {'max_depth': 12, 'min_samples_split': 101, 'min_samples_leaf': 57, 'max_features': 0.392289500350783}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:44:59,271] Trial 307 finished with value: 338607500.0 and parameters: {'max_depth': 16, 'min_samples_split': 518, 'min_samples_leaf': 157, 'max_features': 0.4131009498917939}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:45:13,833] Trial 308 finished with value: 352852500.0 and parameters: {'max_depth': 13, 'min_samples_split': 359, 'min_samples_leaf': 50, 'max_features': 0.37841881203250194}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:45:28,784] Trial 309 finished with value: 334895000.0 and parameters: {'max_depth': 15, 'min_samples_split': 374, 'min_samples_leaf': 49, 'max_features': 0.35655347498948947}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:45:37,662] Trial 310 finished with value: 335417500.0 and parameters: {'max_depth': 7, 'min_samples_split': 366, 'min_samples_leaf': 44, 'max_features': 0.3746431806035085}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:45:44,429] Trial 311 finished with value: 347792500.0 and parameters: {'max_depth': 18, 'min_samples_split': 335, 'min_samples_leaf': 52, 'max_features': 0.1494142712503674}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:45:50,112] Trial 312 finished with value: 336462500.0 and parameters: {'max_depth': 18, 'min_samples_split': 350, 'min_samples_leaf': 52, 'max_features': 0.12337246857849399}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:46:06,989] Trial 313 finished with value: 344712500.0 and parameters: {'max_depth': 18, 'min_samples_split': 432, 'min_samples_leaf': 39, 'max_features': 0.39027013696228136}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:46:30,906] Trial 314 finished with value: 340340000.0 and parameters: {'max_depth': 19, 'min_samples_split': 331, 'min_samples_leaf': 55, 'max_features': 0.5362312636649242}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:46:36,919] Trial 315 finished with value: 322960000.0 and parameters: {'max_depth': 17, 'min_samples_split': 304, 'min_samples_leaf': 149, 'max_features': 0.15380783499308892}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:47:04,162] Trial 316 finished with value: 342485000.0 and parameters: {'max_depth': 16, 'min_samples_split': 772, 'min_samples_leaf': 48, 'max_features': 0.6334280108883728}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:47:29,595] Trial 317 finished with value: 341000000.0 and parameters: {'max_depth': 17, 'min_samples_split': 462, 'min_samples_leaf': 60, 'max_features': 0.5814909399437774}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:47:37,961] Trial 318 finished with value: 335335000.0 and parameters: {'max_depth': 15, 'min_samples_split': 414, 'min_samples_leaf': 50, 'max_features': 0.2026641916300309}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:48:09,153] Trial 319 finished with value: 329532500.0 and parameters: {'max_depth': 26, 'min_samples_split': 45, 'min_samples_leaf': 42, 'max_features': 0.6656633543128044}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:48:26,933] Trial 320 finished with value: 334482500.0 and parameters: {'max_depth': 14, 'min_samples_split': 354, 'min_samples_leaf': 54, 'max_features': 0.4543124396934273}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:48:31,811] Trial 321 finished with value: 296312500.0 and parameters: {'max_depth': 16, 'min_samples_split': 1792, 'min_samples_leaf': 64, 'max_features': 0.11761880895969101}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:48:58,022] Trial 322 finished with value: 342512500.0 and parameters: {'max_depth': 17, 'min_samples_split': 92, 'min_samples_leaf': 58, 'max_features': 0.6096718754555255}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:49:27,586] Trial 323 finished with value: 337810000.0 and parameters: {'max_depth': 31, 'min_samples_split': 29, 'min_samples_leaf': 48, 'max_features': 0.61936529909893}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:49:44,904] Trial 324 finished with value: 344327500.0 and parameters: {'max_depth': 15, 'min_samples_split': 133, 'min_samples_leaf': 53, 'max_features': 0.40129975395525874}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:49:59,682] Trial 325 finished with value: 339295000.0 and parameters: {'max_depth': 19, 'min_samples_split': 388, 'min_samples_leaf': 153, 'max_features': 0.3826918420295549}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:50:08,168] Trial 326 finished with value: 333987500.0 and parameters: {'max_depth': 16, 'min_samples_split': 631, 'min_samples_leaf': 36, 'max_features': 0.1916214075494745}. Best is trial 233 with value: 356372500.0.
[I 2026-09-07 14:50:12,866] Trial 327 finished with value: 335637500.0 and parameters: {'max_depth': 18, 'min_samples_split': 68, 'min_samples_leaf': 44, 'max_features': 0.09368258940114543}. Best is trial 233 with value: 356372500.0.

Best is trial 233 with value: 356372500.

Tarea: 

Mejora 2 Promediar la ganancia OOB sobre varias semillas (evita que Optuna "aprenda" hiperparámetros que solo funcionan bien con semillas[0])

In [54]:
def objective2(trial):
    max_depth = trial.suggest_int('max_depth', 2, 32)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 2000)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 200)
    max_features = trial.suggest_float('max_features', 0.05, 0.7)

    n_semillas_objetivo = 3
    ganancias = []

    for s in semillas[:n_semillas_objetivo]:
        model = RandomForestClassifier(
            n_estimators=100,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            max_features=max_features,
            max_samples=0.7,
            random_state=s,
            n_jobs=-1,
            oob_score=True
        )
        model.fit(Xi, y)
        ganancias.append(ganancia_prob(model.oob_decision_function_, y))

    return np.mean(ganancias)

storage_name = "sqlite:///" + db_path + "optimization2_rf.db"
study_name = "exp_401_random-forest-opt-multiseed"

study2 = optuna.create_study(
    direction="maximize",
    study_name=study_name,
    storage=storage_name,
    load_if_exists=True,
)

[I 2026-09-07 14:55:31,707] Using an existing study with name 'exp_401_random-forest-opt-multiseed' instead of creating a new one.

Mejora 3 (en paralelo)

El bloque 2 no toca la metodología de evaluación (como el bloque 1), sino el espacio de búsqueda: qué hiperparámetros explora Optuna y en qué rangos. Este es el código:


def objective(trial):
    max_depth = trial.suggest_int('max_depth', 2, 32)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 2000, log=True)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 60, log=True)
    max_features = trial.suggest_float('max_features', 0.05, 0.7)
    criterion = trial.suggest_categorical('criterion', ['gini', 'entropy', 'log_loss'])
    class_weight = trial.suggest_categorical('class_weight', [None, 'balanced', 'balanced_subsample'])
    ...
Tres cambios concretos respecto al original:

1. Agrega class_weight

Random Forest, por default, trata todas las filas por igual al decidir cómo partir cada nodo del árbol. El problema: BAJA+2 es una clase minoritaria (poquísimos clientes se dan de baja comparado con los que no). Si todas las filas pesan igual, al árbol "le conviene" ignorar un poco esa clase rara, porque acertar en la mayoría (los que no se van) ya le da buena pureza en el nodo, aunque nunca aprenda a distinguir bien a los que sí se van — que es justo lo que te importa para la ganancia del negocio.

class_weight='balanced' le dice a sklearn: "pesá más los errores en la clase rara, en proporción inversa a cuántas veces aparece". Así el árbol se ve forzado a prestarle más atención a BAJA+2 al elegir sus cortes. 'balanced_subsample' hace lo mismo pero recalculando el peso en cada muestra bootstrap (por árbol) en vez de una sola vez sobre todo el dataset. Agregarlo como hiperparámetro deja que Optuna decida solo si conviene pesar o no (None = sin peso, el comportamiento actual).

2. Agrega criterion

Es la fórmula que usa el árbol para medir qué tan "pura" queda cada partición al elegir dónde cortar (gini es el default de sklearn, entropy/log_loss son alternativas). Con clases desbalanceadas, a veces una fórmula distinta arma cortes ligeramente distintos que ayudan a aislar mejor la clase rara. Es barato probarlo, así que se lo dejamos elegir a Optuna.

3. Achica min_samples_leaf (de 1-200 a 1-60) y usa escala logarítmica en ambos rangos

El rango original permitía hasta 200 muestras mínimas por hoja. Si BAJA+2 es muy rara, exigir 200 muestras por hoja puede obligar al árbol a mezclar esos pocos casos raros con un montón de "no se va", diluyendo la señal. Bajar el techo a 60 le da a Optuna más margen para probar hojas chicas que puedan aislar mejor los clusters de clientes que sí se van.
log=True cambia cómo Optuna muestrea dentro del rango: en vez de repartir intentos uniformemente entre 1 y 60 (desperdiciando pruebas comparando, digamos, 45 vs 50, que se comportan casi igual), concentra más intentos en valores chicos (1, 2, 3, 5, 10...) donde el impacto de cambiar el número es mucho mayor. Es más eficiente la búsqueda.
En resumen: el bloque 1 te da una medición más confiable de "qué tan buena es una combinación de hiperparámetros"; el bloque 2 amplía y afina cuáles combinaciones se prueban, apuntando específicamente al problema de clase desbalanceada que viste en los resultados de la clase.

In [70]:
def objective3(trial):
    max_depth = trial.suggest_int('max_depth', 2, 32)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 2000, log=True)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 60, log=True)
    max_features = trial.suggest_float('max_features', 0.05, 0.7)
    criterion = trial.suggest_categorical('criterion', ['gini', 'entropy', 'log_loss'])
    class_weight = trial.suggest_categorical('class_weight', [None, 'balanced', 'balanced_subsample'])

    model = RandomForestClassifier(
        n_estimators=100,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        max_features=max_features,
        criterion=criterion,
        class_weight=class_weight,
        max_samples=0.7,
        random_state=semillas[0],
        n_jobs=-1,
        oob_score=True
    )

    model.fit(Xi, y)

    return ganancia_prob(model.oob_decision_function_, y)

In [71]:
storage_name = "sqlite:///" + db_path + "optimization_rf.db"
study_name2 = "exp_401_random-forest-opt-searchspace"

study3 = optuna.create_study(
    direction="maximize",
    study_name=study_name2,
    storage=storage_name,
    load_if_exists=True,
)

[I 2026-09-07 16:42:49,848] A new study created in RDB with name: exp_401_random-forest-opt-searchspace

In [55]:
study2.optimize(objective2, n_trials=100)

[I 2026-09-07 14:55:53,198] Trial 0 finished with value: 317496666.6666667 and parameters: {'max_depth': 32, 'min_samples_split': 708, 'min_samples_leaf': 162, 'max_features': 0.18409492193373514}. Best is trial 0 with value: 317496666.6666667.
[I 2026-09-07 14:56:31,520] Trial 1 finished with value: 315333333.3333333 and parameters: {'max_depth': 10, 'min_samples_split': 1447, 'min_samples_leaf': 7, 'max_features': 0.42694688177882933}. Best is trial 0 with value: 317496666.6666667.
[I 2026-09-07 14:57:45,133] Trial 2 finished with value: 313371666.6666667 and parameters: {'max_depth': 13, 'min_samples_split': 1440, 'min_samples_leaf': 4, 'max_features': 0.642863694339371}. Best is trial 0 with value: 317496666.6666667.
[I 2026-09-07 14:58:19,015] Trial 3 finished with value: 321795833.3333333 and parameters: {'max_depth': 6, 'min_samples_split': 1283, 'min_samples_leaf': 155, 'max_features': 0.6391527843758886}. Best is trial 3 with value: 321795833.3333333.
[I 2026-09-07 14:58:48,417] Trial 4 finished with value: 297412500.0 and parameters: {'max_depth': 6, 'min_samples_split': 1988, 'min_samples_leaf': 143, 'max_features': 0.5437591171146303}. Best is trial 3 with value: 321795833.3333333.
[I 2026-09-07 14:59:09,146] Trial 5 finished with value: 306982500.0 and parameters: {'max_depth': 29, 'min_samples_split': 1296, 'min_samples_leaf': 21, 'max_features': 0.16606131884264738}. Best is trial 3 with value: 321795833.3333333.
[I 2026-09-07 14:59:54,349] Trial 6 finished with value: 330018333.3333333 and parameters: {'max_depth': 16, 'min_samples_split': 604, 'min_samples_leaf': 15, 'max_features': 0.35576660063320226}. Best is trial 6 with value: 330018333.3333333.
[I 2026-09-07 15:00:48,899] Trial 7 finished with value: 301693333.3333333 and parameters: {'max_depth': 24, 'min_samples_split': 1846, 'min_samples_leaf': 86, 'max_features': 0.48685715356497283}. Best is trial 6 with value: 330018333.3333333.
[I 2026-09-07 15:01:08,055] Trial 8 finished with value: 296789166.6666667 and parameters: {'max_depth': 9, 'min_samples_split': 1664, 'min_samples_leaf': 105, 'max_features': 0.2264876227667282}. Best is trial 6 with value: 330018333.3333333.
[I 2026-09-07 15:01:54,520] Trial 9 finished with value: 338644166.6666667 and parameters: {'max_depth': 7, 'min_samples_split': 291, 'min_samples_leaf': 194, 'max_features': 0.6998951919419872}. Best is trial 9 with value: 338644166.6666667.
[I 2026-09-07 15:02:29,363] Trial 10 finished with value: 341009166.6666667 and parameters: {'max_depth': 20, 'min_samples_split': 138, 'min_samples_leaf': 195, 'max_features': 0.3065073241241296}. Best is trial 10 with value: 341009166.6666667.
[I 2026-09-07 15:03:06,094] Trial 11 finished with value: 336994166.6666667 and parameters: {'max_depth': 19, 'min_samples_split': 76, 'min_samples_leaf': 196, 'max_features': 0.3283214056895435}. Best is trial 10 with value: 341009166.6666667.
[I 2026-09-07 15:03:11,548] Trial 12 finished with value: 175715833.33333334 and parameters: {'max_depth': 2, 'min_samples_split': 79, 'min_samples_leaf': 197, 'max_features': 0.07899931494703283}. Best is trial 10 with value: 341009166.6666667.
[I 2026-09-07 15:04:28,122] Trial 13 finished with value: 341183333.3333333 and parameters: {'max_depth': 22, 'min_samples_split': 443, 'min_samples_leaf': 178, 'max_features': 0.6830363258047158}. Best is trial 13 with value: 341183333.3333333.
[I 2026-09-07 15:05:00,969] Trial 14 finished with value: 329349166.6666667 and parameters: {'max_depth': 22, 'min_samples_split': 612, 'min_samples_leaf': 125, 'max_features': 0.2944595098984771}. Best is trial 13 with value: 341183333.3333333.
[I 2026-09-07 15:05:59,334] Trial 15 finished with value: 336315833.3333333 and parameters: {'max_depth': 26, 'min_samples_split': 894, 'min_samples_leaf': 175, 'max_features': 0.5420138233597255}. Best is trial 13 with value: 341183333.3333333.
[I 2026-09-07 15:06:09,905] Trial 16 finished with value: 312785000.0 and parameters: {'max_depth': 19, 'min_samples_split': 314, 'min_samples_leaf': 132, 'max_features': 0.07186795887832109}. Best is trial 13 with value: 341183333.3333333.
[I 2026-09-07 15:06:54,340] Trial 17 finished with value: 340294166.6666667 and parameters: {'max_depth': 20, 'min_samples_split': 369, 'min_samples_leaf': 176, 'max_features': 0.410389811664013}. Best is trial 13 with value: 341183333.3333333.
[I 2026-09-07 15:07:24,095] Trial 18 finished with value: 327589166.6666667 and parameters: {'max_depth': 15, 'min_samples_split': 898, 'min_samples_leaf': 65, 'max_features': 0.2550169040844443}. Best is trial 13 with value: 341183333.3333333.
[I 2026-09-07 15:08:25,690] Trial 19 finished with value: 338149166.6666667 and parameters: {'max_depth': 27, 'min_samples_split': 7, 'min_samples_leaf': 175, 'max_features': 0.5739117035117917}. Best is trial 13 with value: 341183333.3333333.
[I 2026-09-07 15:09:08,680] Trial 20 finished with value: 342732500.0 and parameters: {'max_depth': 23, 'min_samples_split': 436, 'min_samples_leaf': 154, 'max_features': 0.3887631918743707}. Best is trial 20 with value: 342732500.0.
[I 2026-09-07 15:09:53,931] Trial 21 finished with value: 334629166.6666667 and parameters: {'max_depth': 23, 'min_samples_split': 430, 'min_samples_leaf': 155, 'max_features': 0.4047643688887379}. Best is trial 20 with value: 342732500.0.
[I 2026-09-07 15:10:48,818] Trial 22 finished with value: 336765000.0 and parameters: {'max_depth': 18, 'min_samples_split': 865, 'min_samples_leaf': 116, 'max_features': 0.48330403532635513}. Best is trial 20 with value: 342732500.0.
[I 2026-09-07 15:11:25,982] Trial 23 finished with value: 339221666.6666667 and parameters: {'max_depth': 22, 'min_samples_split': 188, 'min_samples_leaf': 179, 'max_features': 0.3534062460032214}. Best is trial 20 with value: 342732500.0.
[I 2026-09-07 15:11:41,242] Trial 24 finished with value: 318028333.3333333 and parameters: {'max_depth': 26, 'min_samples_split': 499, 'min_samples_leaf': 142, 'max_features': 0.12771376526150785}. Best is trial 20 with value: 342732500.0.
[I 2026-09-07 15:12:12,200] Trial 25 finished with value: 339340833.3333333 and parameters: {'max_depth': 30, 'min_samples_split': 197, 'min_samples_leaf': 166, 'max_features': 0.2845893508052307}. Best is trial 20 with value: 342732500.0.
[I 2026-09-07 15:13:00,485] Trial 26 finished with value: 337040000.0 and parameters: {'max_depth': 16, 'min_samples_split': 741, 'min_samples_leaf': 186, 'max_features': 0.4693023417226958}. Best is trial 20 with value: 342732500.0.
[I 2026-09-07 15:13:24,379] Trial 27 finished with value: 304379166.6666667 and parameters: {'max_depth': 21, 'min_samples_split': 1080, 'min_samples_leaf': 146, 'max_features': 0.21599724142734283}. Best is trial 20 with value: 342732500.0.
[I 2026-09-07 15:14:38,587] Trial 28 finished with value: 337590000.0 and parameters: {'max_depth': 25, 'min_samples_split': 513, 'min_samples_leaf': 104, 'max_features': 0.6261965459423594}. Best is trial 20 with value: 342732500.0.
[I 2026-09-07 15:14:57,404] Trial 29 finished with value: 316690000.0 and parameters: {'max_depth': 31, 'min_samples_split': 688, 'min_samples_leaf': 164, 'max_features': 0.1687524801646609}. Best is trial 20 with value: 342732500.0.
[I 2026-09-07 15:16:06,719] Trial 30 finished with value: 340532500.0 and parameters: {'max_depth': 28, 'min_samples_split': 214, 'min_samples_leaf': 165, 'max_features': 0.6864981248481394}. Best is trial 20 with value: 342732500.0.
[I 2026-09-07 15:17:16,353] Trial 31 finished with value: 341605000.0 and parameters: {'max_depth': 29, 'min_samples_split': 275, 'min_samples_leaf': 164, 'max_features': 0.6977646924376855}. Best is trial 20 with value: 342732500.0.
[I 2026-09-07 15:18:14,232] Trial 32 finished with value: 345620000.0 and parameters: {'max_depth': 24, 'min_samples_split': 493, 'min_samples_leaf': 186, 'max_features': 0.5952018760598139}. Best is trial 32 with value: 345620000.0.
[I 2026-09-07 15:19:12,767] Trial 33 finished with value: 345235000.0 and parameters: {'max_depth': 31, 'min_samples_split': 462, 'min_samples_leaf': 154, 'max_features': 0.5835316440105153}. Best is trial 32 with value: 345620000.0.
[I 2026-09-07 15:20:13,827] Trial 34 finished with value: 336224166.6666667 and parameters: {'max_depth': 32, 'min_samples_split': 777, 'min_samples_leaf': 151, 'max_features': 0.6067728787830566}. Best is trial 32 with value: 345620000.0.
[I 2026-09-07 15:21:14,381] Trial 35 finished with value: 347004166.6666667 and parameters: {'max_depth': 29, 'min_samples_split': 569, 'min_samples_leaf': 132, 'max_features': 0.5884561320433115}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:22:10,448] Trial 36 finished with value: 338726666.6666667 and parameters: {'max_depth': 32, 'min_samples_split': 605, 'min_samples_leaf': 134, 'max_features': 0.5364066932058134}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:23:14,810] Trial 37 finished with value: 335170000.0 and parameters: {'max_depth': 28, 'min_samples_split': 994, 'min_samples_leaf': 84, 'max_features': 0.5858522975744849}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:24:08,597] Trial 38 finished with value: 333969166.6666667 and parameters: {'max_depth': 26, 'min_samples_split': 532, 'min_samples_leaf': 118, 'max_features': 0.5022549250574796}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:25:17,691] Trial 39 finished with value: 339845000.0 and parameters: {'max_depth': 24, 'min_samples_split': 398, 'min_samples_leaf': 140, 'max_features': 0.6555186400483232}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:26:03,739] Trial 40 finished with value: 327240833.3333333 and parameters: {'max_depth': 30, 'min_samples_split': 1168, 'min_samples_leaf': 155, 'max_features': 0.4474748392743087}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:27:12,026] Trial 41 finished with value: 341064166.6666667 and parameters: {'max_depth': 29, 'min_samples_split': 653, 'min_samples_leaf': 159, 'max_features': 0.6588996099905992}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:28:09,347] Trial 42 finished with value: 341183333.3333333 and parameters: {'max_depth': 28, 'min_samples_split': 272, 'min_samples_leaf': 185, 'max_features': 0.5668842033346164}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:29:15,155] Trial 43 finished with value: 338534166.6666667 and parameters: {'max_depth': 30, 'min_samples_split': 322, 'min_samples_leaf': 133, 'max_features': 0.6163682646261375}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:30:09,202] Trial 44 finished with value: 336774166.6666667 and parameters: {'max_depth': 24, 'min_samples_split': 536, 'min_samples_leaf': 169, 'max_features': 0.5294349060001895}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:31:05,510] Trial 45 finished with value: 336820000.0 and parameters: {'max_depth': 27, 'min_samples_split': 814, 'min_samples_leaf': 187, 'max_features': 0.6003217514819058}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:32:16,449] Trial 46 finished with value: 339661666.6666667 and parameters: {'max_depth': 31, 'min_samples_split': 409, 'min_samples_leaf': 106, 'max_features': 0.650277635987365}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:33:10,160] Trial 47 finished with value: 339854166.6666667 and parameters: {'max_depth': 25, 'min_samples_split': 703, 'min_samples_leaf': 125, 'max_features': 0.5042485448805561}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:34:08,692] Trial 48 finished with value: 316231666.6666667 and parameters: {'max_depth': 29, 'min_samples_split': 1574, 'min_samples_leaf': 147, 'max_features': 0.5744410453665522}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:35:16,969] Trial 49 finished with value: 339075000.0 and parameters: {'max_depth': 32, 'min_samples_split': 108, 'min_samples_leaf': 156, 'max_features': 0.6703721143268189}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:36:31,410] Trial 50 finished with value: 341916666.6666667 and parameters: {'max_depth': 27, 'min_samples_split': 272, 'min_samples_leaf': 59, 'max_features': 0.6275399780408075}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:37:46,236] Trial 51 finished with value: 341091666.6666667 and parameters: {'max_depth': 27, 'min_samples_split': 463, 'min_samples_leaf': 58, 'max_features': 0.6364124122897367}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:38:54,993] Trial 52 finished with value: 337021666.6666667 and parameters: {'max_depth': 25, 'min_samples_split': 280, 'min_samples_leaf': 35, 'max_features': 0.5518534582518715}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:40:43,010] Trial 53 finished with value: 289565833.3333333 and parameters: {'max_depth': 23, 'min_samples_split': 588, 'min_samples_leaf': 2, 'max_features': 0.6996045121406291}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:42:02,068] Trial 54 finished with value: 338030000.0 and parameters: {'max_depth': 29, 'min_samples_split': 371, 'min_samples_leaf': 25, 'max_features': 0.603880900702925}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:42:56,574] Trial 55 finished with value: 343887500.0 and parameters: {'max_depth': 11, 'min_samples_split': 36, 'min_samples_leaf': 49, 'max_features': 0.6332121644325642}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:43:41,908] Trial 56 finished with value: 342118333.3333333 and parameters: {'max_depth': 11, 'min_samples_split': 28, 'min_samples_leaf': 47, 'max_features': 0.512240462355462}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:44:15,919] Trial 57 finished with value: 345720833.3333333 and parameters: {'max_depth': 11, 'min_samples_split': 49, 'min_samples_leaf': 78, 'max_features': 0.381166520100292}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:44:54,057] Trial 58 finished with value: 342686666.6666667 and parameters: {'max_depth': 13, 'min_samples_split': 142, 'min_samples_leaf': 85, 'max_features': 0.3820088910389396}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:45:15,276] Trial 59 finished with value: 334748333.3333333 and parameters: {'max_depth': 7, 'min_samples_split': 42, 'min_samples_leaf': 72, 'max_features': 0.33044143791029396}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:45:51,573] Trial 60 finished with value: 345225833.3333333 and parameters: {'max_depth': 10, 'min_samples_split': 150, 'min_samples_leaf': 46, 'max_features': 0.4357890106515889}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:46:24,960] Trial 61 finished with value: 339111666.6666667 and parameters: {'max_depth': 9, 'min_samples_split': 148, 'min_samples_leaf': 40, 'max_features': 0.43785252600584346}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:46:38,081] Trial 62 finished with value: 255273333.33333334 and parameters: {'max_depth': 3, 'min_samples_split': 90, 'min_samples_leaf': 10, 'max_features': 0.38791455523051455}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:47:20,370] Trial 63 finished with value: 339001666.6666667 and parameters: {'max_depth': 12, 'min_samples_split': 348, 'min_samples_leaf': 75, 'max_features': 0.4588061592832548}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:47:37,704] Trial 64 finished with value: 310062500.0 and parameters: {'max_depth': 5, 'min_samples_split': 202, 'min_samples_leaf': 97, 'max_features': 0.3581951763425785}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:48:13,805] Trial 65 finished with value: 346866666.6666667 and parameters: {'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 50, 'max_features': 0.3226790916104285}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:48:34,888] Trial 66 finished with value: 344758333.3333333 and parameters: {'max_depth': 9, 'min_samples_split': 20, 'min_samples_leaf': 49, 'max_features': 0.25524624494937354}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:49:05,289] Trial 67 finished with value: 337837500.0 and parameters: {'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 25, 'max_features': 0.25846175808313243}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:49:25,911] Trial 68 finished with value: 333960000.0 and parameters: {'max_depth': 7, 'min_samples_split': 226, 'min_samples_leaf': 37, 'max_features': 0.31024274744261215}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:49:43,266] Trial 69 finished with value: 341485833.3333333 and parameters: {'max_depth': 9, 'min_samples_split': 143, 'min_samples_leaf': 69, 'max_features': 0.20614078527480645}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:50:06,509] Trial 70 finished with value: 297861666.6666667 and parameters: {'max_depth': 10, 'min_samples_split': 1849, 'min_samples_leaf': 51, 'max_features': 0.2786060334897861}. Best is trial 35 with value: 347004166.6666667.
[I 2026-09-07 15:50:48,080] Trial 71 finished with value: 352889166.6666667 and parameters: {'max_depth': 13, 'min_samples_split': 50, 'min_samples_leaf': 53, 'max_features': 0.41542696991016825}. Best is trial 71 with value: 352889166.6666667.
[I 2026-09-07 15:51:31,302] Trial 72 finished with value: 351101666.6666667 and parameters: {'max_depth': 15, 'min_samples_split': 88, 'min_samples_leaf': 58, 'max_features': 0.40595638108250903}. Best is trial 71 with value: 352889166.6666667.
[I 2026-09-07 15:52:17,574] Trial 73 finished with value: 342540000.0 and parameters: {'max_depth': 17, 'min_samples_split': 95, 'min_samples_leaf': 63, 'max_features': 0.4165581776364432}. Best is trial 71 with value: 352889166.6666667.
[I 2026-09-07 15:52:55,239] Trial 74 finished with value: 349002500.0 and parameters: {'max_depth': 14, 'min_samples_split': 222, 'min_samples_leaf': 42, 'max_features': 0.35301208929961453}. Best is trial 71 with value: 352889166.6666667.
[I 2026-09-07 15:53:34,293] Trial 75 finished with value: 342265000.0 and parameters: {'max_depth': 14, 'min_samples_split': 232, 'min_samples_leaf': 33, 'max_features': 0.36679926331226564}. Best is trial 71 with value: 352889166.6666667.
[I 2026-09-07 15:54:07,545] Trial 76 finished with value: 338845833.3333333 and parameters: {'max_depth': 14, 'min_samples_split': 477, 'min_samples_leaf': 78, 'max_features': 0.3342664022243934}. Best is trial 71 with value: 352889166.6666667.
[I 2026-09-07 15:54:45,851] Trial 77 finished with value: 336755833.3333333 and parameters: {'max_depth': 17, 'min_samples_split': 557, 'min_samples_leaf': 200, 'max_features': 0.40486805496274403}. Best is trial 71 with value: 352889166.6666667.
[I 2026-09-07 15:55:19,834] Trial 78 finished with value: 345418333.3333333 and parameters: {'max_depth': 13, 'min_samples_split': 327, 'min_samples_leaf': 92, 'max_features': 0.3490116090039083}. Best is trial 71 with value: 352889166.6666667.
[I 2026-09-07 15:55:51,013] Trial 79 finished with value: 343181666.6666667 and parameters: {'max_depth': 13, 'min_samples_split': 71, 'min_samples_leaf': 58, 'max_features': 0.30474184113968117}. Best is trial 71 with value: 352889166.6666667.
[I 2026-09-07 15:56:27,040] Trial 80 finished with value: 340046666.6666667 and parameters: {'max_depth': 15, 'min_samples_split': 332, 'min_samples_leaf': 95, 'max_features': 0.34427748975269007}. Best is trial 71 with value: 352889166.6666667.
[I 2026-09-07 15:58:24,742] Trial 81 finished with value: 334051666.6666667 and parameters: {'max_depth': 13, 'min_samples_split': 650, 'min_samples_leaf': 69, 'max_features': 0.3688017212818124}. Best is trial 71 with value: 352889166.6666667.

In [72]:
study3.optimize(objective3, n_trials=100)

[I 2026-09-07 16:43:26,044] Trial 0 finished with value: 111045000.0 and parameters: {'max_depth': 25, 'min_samples_split': 13, 'min_samples_leaf': 1, 'max_features': 0.6686587709811007, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 0 with value: 111045000.0.
[I 2026-09-07 16:43:31,278] Trial 1 finished with value: 291582500.0 and parameters: {'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 42, 'max_features': 0.343011939765005, 'criterion': 'gini', 'class_weight': None}. Best is trial 1 with value: 291582500.0.
[I 2026-09-07 16:43:47,219] Trial 2 finished with value: 352082500.0 and parameters: {'max_depth': 11, 'min_samples_split': 29, 'min_samples_leaf': 29, 'max_features': 0.5983917329186031, 'criterion': 'entropy', 'class_weight': None}. Best is trial 2 with value: 352082500.0.
[I 2026-09-07 16:44:00,036] Trial 3 finished with value: 352770000.0 and parameters: {'max_depth': 20, 'min_samples_split': 778, 'min_samples_leaf': 2, 'max_features': 0.45509383942277526, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:44:07,842] Trial 4 finished with value: -1461900000.0 and parameters: {'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 3, 'max_features': 0.2773701592011447, 'criterion': 'log_loss', 'class_weight': 'balanced'}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:44:15,538] Trial 5 finished with value: -3398972500.0 and parameters: {'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 23, 'max_features': 0.5325642687441884, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:44:29,159] Trial 6 finished with value: -1241075000.0 and parameters: {'max_depth': 16, 'min_samples_split': 17, 'min_samples_leaf': 44, 'max_features': 0.41992580671368573, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:44:32,510] Trial 7 finished with value: 319357500.0 and parameters: {'max_depth': 12, 'min_samples_split': 300, 'min_samples_leaf': 9, 'max_features': 0.0710095705228132, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:44:36,840] Trial 8 finished with value: 262982500.0 and parameters: {'max_depth': 25, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.09761747063945708, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:44:50,862] Trial 9 finished with value: 120807500.0 and parameters: {'max_depth': 32, 'min_samples_split': 12, 'min_samples_leaf': 4, 'max_features': 0.4947498546148108, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:44:57,029] Trial 10 finished with value: 319990000.0 and parameters: {'max_depth': 20, 'min_samples_split': 1815, 'min_samples_leaf': 1, 'max_features': 0.21805934773350386, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:45:14,204] Trial 11 finished with value: 345125000.0 and parameters: {'max_depth': 11, 'min_samples_split': 83, 'min_samples_leaf': 12, 'max_features': 0.6612230369312102, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:45:27,929] Trial 12 finished with value: 329010000.0 and parameters: {'max_depth': 19, 'min_samples_split': 1933, 'min_samples_leaf': 9, 'max_features': 0.5645280016721356, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:45:41,483] Trial 13 finished with value: 305882500.0 and parameters: {'max_depth': 24, 'min_samples_split': 122, 'min_samples_leaf': 1, 'max_features': 0.44512623102774895, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:45:57,080] Trial 14 finished with value: 347765000.0 and parameters: {'max_depth': 15, 'min_samples_split': 437, 'min_samples_leaf': 19, 'max_features': 0.6024710590298306, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:46:05,970] Trial 15 finished with value: -2503627500.0 and parameters: {'max_depth': 7, 'min_samples_split': 48, 'min_samples_leaf': 5, 'max_features': 0.3970961206274948, 'criterion': 'entropy', 'class_weight': 'balanced_subsample'}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:46:32,085] Trial 16 finished with value: 286852500.0 and parameters: {'max_depth': 30, 'min_samples_split': 358, 'min_samples_leaf': 2, 'max_features': 0.4842180118559817, 'criterion': 'gini', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:46:47,702] Trial 17 finished with value: 343502500.0 and parameters: {'max_depth': 21, 'min_samples_split': 39, 'min_samples_leaf': 24, 'max_features': 0.6119185459188886, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:46:58,035] Trial 18 finished with value: -205397500.0 and parameters: {'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.34727135108638657, 'criterion': 'entropy', 'class_weight': 'balanced_subsample'}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:47:03,038] Trial 19 finished with value: -2748735000.0 and parameters: {'max_depth': 8, 'min_samples_split': 895, 'min_samples_leaf': 54, 'max_features': 0.18523228929525254, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:47:18,174] Trial 20 finished with value: 344795000.0 and parameters: {'max_depth': 14, 'min_samples_split': 163, 'min_samples_leaf': 6, 'max_features': 0.5367622777546732, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:47:34,261] Trial 21 finished with value: 350157500.0 and parameters: {'max_depth': 16, 'min_samples_split': 588, 'min_samples_leaf': 20, 'max_features': 0.6334450837823141, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:47:49,440] Trial 22 finished with value: 348837500.0 and parameters: {'max_depth': 18, 'min_samples_split': 896, 'min_samples_leaf': 15, 'max_features': 0.6187357538087995, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:48:07,137] Trial 23 finished with value: 348370000.0 and parameters: {'max_depth': 22, 'min_samples_split': 683, 'min_samples_leaf': 30, 'max_features': 0.6948982445965743, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:48:22,314] Trial 24 finished with value: 350817500.0 and parameters: {'max_depth': 13, 'min_samples_split': 224, 'min_samples_leaf': 31, 'max_features': 0.5715918398314468, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:48:32,707] Trial 25 finished with value: 337672500.0 and parameters: {'max_depth': 7, 'min_samples_split': 227, 'min_samples_leaf': 34, 'max_features': 0.48741022387502325, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:48:47,979] Trial 26 finished with value: 340862500.0 and parameters: {'max_depth': 13, 'min_samples_split': 59, 'min_samples_leaf': 8, 'max_features': 0.5702535113823486, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:48:51,240] Trial 27 finished with value: 258335000.0 and parameters: {'max_depth': 2, 'min_samples_split': 29, 'min_samples_leaf': 15, 'max_features': 0.36948074820118293, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:49:03,691] Trial 28 finished with value: -1856470000.0 and parameters: {'max_depth': 9, 'min_samples_split': 120, 'min_samples_leaf': 55, 'max_features': 0.520939354020476, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:49:16,359] Trial 29 finished with value: -2970000.0 and parameters: {'max_depth': 29, 'min_samples_split': 21, 'min_samples_leaf': 1, 'max_features': 0.45434061018819355, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:49:31,255] Trial 30 finished with value: -2278100000.0 and parameters: {'max_depth': 25, 'min_samples_split': 1203, 'min_samples_leaf': 33, 'max_features': 0.6714062522888491, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:49:46,740] Trial 31 finished with value: 351505000.0 and parameters: {'max_depth': 17, 'min_samples_split': 519, 'min_samples_leaf': 23, 'max_features': 0.6370352526014659, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:50:02,166] Trial 32 finished with value: 344080000.0 and parameters: {'max_depth': 17, 'min_samples_split': 248, 'min_samples_leaf': 14, 'max_features': 0.5770576983182062, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:50:17,659] Trial 33 finished with value: 345730000.0 and parameters: {'max_depth': 13, 'min_samples_split': 503, 'min_samples_leaf': 28, 'max_features': 0.6493138895558187, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:50:30,657] Trial 34 finished with value: 338937500.0 and parameters: {'max_depth': 22, 'min_samples_split': 1063, 'min_samples_leaf': 40, 'max_features': 0.5499160881086848, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:50:49,006] Trial 35 finished with value: 313995000.0 and parameters: {'max_depth': 10, 'min_samples_split': 169, 'min_samples_leaf': 2, 'max_features': 0.6940539459286897, 'criterion': 'gini', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:51:04,903] Trial 36 finished with value: 325022500.0 and parameters: {'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 11, 'max_features': 0.5953913260654634, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:51:13,677] Trial 37 finished with value: -1413967500.0 and parameters: {'max_depth': 12, 'min_samples_split': 72, 'min_samples_leaf': 44, 'max_features': 0.3137820763256315, 'criterion': 'entropy', 'class_weight': 'balanced_subsample'}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:51:19,844] Trial 38 finished with value: -3416875000.0 and parameters: {'max_depth': 4, 'min_samples_split': 1374, 'min_samples_leaf': 26, 'max_features': 0.4227480095276103, 'criterion': 'log_loss', 'class_weight': 'balanced'}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:51:33,695] Trial 39 finished with value: 345372500.0 and parameters: {'max_depth': 14, 'min_samples_split': 336, 'min_samples_leaf': 18, 'max_features': 0.5105887670210052, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:51:47,856] Trial 40 finished with value: 281847500.0 and parameters: {'max_depth': 20, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': 0.46923576512944154, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:52:03,413] Trial 41 finished with value: 348727500.0 and parameters: {'max_depth': 16, 'min_samples_split': 641, 'min_samples_leaf': 22, 'max_features': 0.6117698966612659, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:52:19,016] Trial 42 finished with value: 348012500.0 and parameters: {'max_depth': 11, 'min_samples_split': 574, 'min_samples_leaf': 19, 'max_features': 0.6435878961565082, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:52:34,204] Trial 43 finished with value: 349140000.0 and parameters: {'max_depth': 18, 'min_samples_split': 776, 'min_samples_leaf': 58, 'max_features': 0.6404751985909448, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 352770000.0.
[I 2026-09-07 16:52:48,036] Trial 44 finished with value: 357967500.0 and parameters: {'max_depth': 15, 'min_samples_split': 439, 'min_samples_leaf': 44, 'max_features': 0.5431485655651028, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:53:01,985] Trial 45 finished with value: 347297500.0 and parameters: {'max_depth': 14, 'min_samples_split': 234, 'min_samples_leaf': 41, 'max_features': 0.5507819093139102, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:53:15,964] Trial 46 finished with value: 351257500.0 and parameters: {'max_depth': 11, 'min_samples_split': 410, 'min_samples_leaf': 36, 'max_features': 0.57944753752109, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:53:28,561] Trial 47 finished with value: -1920242500.0 and parameters: {'max_depth': 10, 'min_samples_split': 361, 'min_samples_leaf': 1, 'max_features': 0.5214701985514598, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:53:35,474] Trial 48 finished with value: 316085000.0 and parameters: {'max_depth': 5, 'min_samples_split': 1614, 'min_samples_leaf': 48, 'max_features': 0.41228400684647326, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:53:50,780] Trial 49 finished with value: 349002500.0 and parameters: {'max_depth': 23, 'min_samples_split': 3, 'min_samples_leaf': 36, 'max_features': 0.5798001714582268, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:54:03,602] Trial 50 finished with value: -1814505000.0 and parameters: {'max_depth': 27, 'min_samples_split': 418, 'min_samples_leaf': 7, 'max_features': 0.5054998005731677, 'criterion': 'log_loss', 'class_weight': 'balanced'}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:54:21,887] Trial 51 finished with value: 337287500.0 and parameters: {'max_depth': 12, 'min_samples_split': 104, 'min_samples_leaf': 28, 'max_features': 0.5832128139338936, 'criterion': 'gini', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:54:39,834] Trial 52 finished with value: 348535000.0 and parameters: {'max_depth': 15, 'min_samples_split': 196, 'min_samples_leaf': 4, 'max_features': 0.6692403540224873, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:54:53,474] Trial 53 finished with value: 345510000.0 and parameters: {'max_depth': 20, 'min_samples_split': 482, 'min_samples_leaf': 46, 'max_features': 0.5457659492754398, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:55:07,038] Trial 54 finished with value: 341962500.0 and parameters: {'max_depth': 8, 'min_samples_split': 278, 'min_samples_leaf': 24, 'max_features': 0.6093128116489155, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:55:18,888] Trial 55 finished with value: 348287500.0 and parameters: {'max_depth': 15, 'min_samples_split': 16, 'min_samples_leaf': 35, 'max_features': 0.453195567841845, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:55:32,196] Trial 56 finished with value: 341550000.0 and parameters: {'max_depth': 11, 'min_samples_split': 983, 'min_samples_leaf': 17, 'max_features': 0.5578185809361704, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:55:37,066] Trial 57 finished with value: 337700000.0 and parameters: {'max_depth': 17, 'min_samples_split': 396, 'min_samples_leaf': 11, 'max_features': 0.13874136920805738, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:55:55,236] Trial 58 finished with value: -1349755000.0 and parameters: {'max_depth': 13, 'min_samples_split': 146, 'min_samples_leaf': 31, 'max_features': 0.6307853311210536, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:56:06,784] Trial 59 finished with value: 341330000.0 and parameters: {'max_depth': 19, 'min_samples_split': 766, 'min_samples_leaf': 50, 'max_features': 0.49018269453342495, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:56:19,055] Trial 60 finished with value: 353512500.0 and parameters: {'max_depth': 9, 'min_samples_split': 288, 'min_samples_leaf': 22, 'max_features': 0.5244105260859737, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:56:31,736] Trial 61 finished with value: 351697500.0 and parameters: {'max_depth': 9, 'min_samples_split': 282, 'min_samples_leaf': 23, 'max_features': 0.5323114390953778, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:56:41,472] Trial 62 finished with value: 325407500.0 and parameters: {'max_depth': 6, 'min_samples_split': 554, 'min_samples_leaf': 21, 'max_features': 0.5289856054857414, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:56:52,783] Trial 63 finished with value: 346252500.0 and parameters: {'max_depth': 9, 'min_samples_split': 94, 'min_samples_leaf': 23, 'max_features': 0.47172033319889073, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:57:02,804] Trial 64 finished with value: 348067500.0 and parameters: {'max_depth': 8, 'min_samples_split': 335, 'min_samples_leaf': 13, 'max_features': 0.43659388330141535, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:57:12,640] Trial 65 finished with value: 341110000.0 and parameters: {'max_depth': 10, 'min_samples_split': 31, 'min_samples_leaf': 60, 'max_features': 0.3921836732228058, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:57:24,531] Trial 66 finished with value: 340587500.0 and parameters: {'max_depth': 7, 'min_samples_split': 740, 'min_samples_leaf': 39, 'max_features': 0.5904398831040155, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:57:35,476] Trial 67 finished with value: -2414335000.0 and parameters: {'max_depth': 9, 'min_samples_split': 1440, 'min_samples_leaf': 2, 'max_features': 0.49881051131817894, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:57:47,271] Trial 68 finished with value: 347462500.0 and parameters: {'max_depth': 11, 'min_samples_split': 293, 'min_samples_leaf': 16, 'max_features': 0.4698348129406097, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:57:57,364] Trial 69 finished with value: 317845000.0 and parameters: {'max_depth': 6, 'min_samples_split': 1949, 'min_samples_leaf': 27, 'max_features': 0.5430789715600531, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 357967500.0.
[I 2026-09-07 16:58:12,145] Trial 70 finished with value: 353210000.0 and parameters: {'max_depth': 12, 'min_samples_split': 479, 'min_samples_leaf': 1, 'max_features': 0.5635718779176649, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 357967500.0.

Exploramos como fue la búsqueda de parámetros

In [16]:
import sys, nbformat
print(sys.executable)
print(nbformat.__version__)

/Library/Developer/CommandLineTools/usr/bin/python3
5.10.4

In [10]:
optuna.visualization.plot_optimization_history(study)

In [56]:
optuna.visualization.plot_optimization_history(study2)

In [11]:
plot_param_importances(study)

In [57]:
plot_param_importances(study2)

In [12]:
plot_slice(study)

In [58]:
plot_slice(study2)

In [13]:
plot_contour(study)

In [59]:
plot_contour(study2)

In [14]:
plot_contour(study, params=["max_depth", "min_samples_split"])

In [60]:
plot_contour(study2, params=["max_depth", "min_samples_split"])

Ajustamos el mejor modelo a todo el conjunto de datos

In [15]:
model_rf = RandomForestClassifier(
        n_estimators=100,
        **study.best_params,
        max_samples=0.7,
        random_state=semillas[0],
        n_jobs=-1,
        oob_score=True
    )

model_rf.fit(Xi, y)

RandomForestClassifier(max_depth=15, max_features=0.6245837962050735,
                       max_samples=0.7, min_samples_leaf=53,
                       min_samples_split=339, n_jobs=-1, oob_score=True,
                       random_state=713929)

In [65]:
model_rf2 = RandomForestClassifier(
        n_estimators=100,
        **study2.best_params,
        max_samples=0.7,
        random_state=semillas[0],
        n_jobs=-1,
        oob_score=True
    )

model_rf2.fit(Xi, y)

RandomForestClassifier(max_depth=13, max_features=0.41542696991016825,
                       max_samples=0.7, min_samples_leaf=53,
                       min_samples_split=50, n_jobs=-1, oob_score=True,
                       random_state=808840)

In [73]:
model_rf3 = RandomForestClassifier(
        n_estimators=100,
        **study3.best_params,
        max_samples=0.7,
        random_state=semillas[0],
        n_jobs=-1,
        oob_score=True
    )

model_rf3.fit(Xi, y)

RandomForestClassifier(criterion='entropy', max_depth=12,
                       max_features=0.5423023481240334, max_samples=0.7,
                       min_samples_leaf=27, min_samples_split=210, n_jobs=-1,
                       oob_score=True, random_state=808840)

Guardamos el modelo, para no tener que optimizar cada vez que lo queramos usar.

In [16]:
filename = modelos_path + 'exp_206_random_forest_model_100.sav'
pickle.dump(model_rf, open(filename, 'wb'))

In [66]:
filename = modelos_path + 'exp_71_random_forest_model_100.sav'
pickle.dump(model_rf2, open(filename, 'wb'))

In [74]:
filename = modelos_path + 'exp_91_random_forest_model_100.sav'
pickle.dump(model_rf3, open(filename, 'wb'))

Y lo cargamos para utilizarlo

In [17]:
model_rf = pickle.load(open(filename, 'rb'))
model_rf

RandomForestClassifier(max_depth=15, max_features=0.6245837962050735,
                       max_samples=0.7, min_samples_leaf=53,
                       min_samples_split=339, n_jobs=-1, oob_score=True,
                       random_state=713929)

In [67]:
model_rf2 = pickle.load(open(filename, 'rb'))
model_rf2

RandomForestClassifier(max_depth=13, max_features=0.41542696991016825,
                       max_samples=0.7, min_samples_leaf=53,
                       min_samples_split=50, n_jobs=-1, oob_score=True,
                       random_state=808840)

In [75]:
model_rf3 = pickle.load(open(filename, 'rb'))
model_rf3

RandomForestClassifier(criterion='entropy', max_depth=12,
                       max_features=0.5423023481240334, max_samples=0.7,
                       min_samples_leaf=27, min_samples_split=210, n_jobs=-1,
                       oob_score=True, random_state=808840)

Ahora vamos medir su ganancia sobre el dataset de **Mayo**

In [18]:
y_pred_rf = model_rf.predict_proba(Xif)
ganancias_rf = ganancia_prob(y_pred_rf, y_futuro)
print(f"Ganancia de modelo RF: {ganancias_rf}")

Ganancia de modelo RF: 253137500.0

In [68]:
y_pred_rf2 = model_rf2.predict_proba(Xif)
ganancias_rf2 = ganancia_prob(y_pred_rf2, y_futuro)
print(f"Ganancia de modelo RF: {ganancias_rf2}")

Ganancia de modelo RF: 254732500.0

In [76]:
y_pred_rf3 = model_rf3.predict_proba(Xif)
ganancias_rf3 = ganancia_prob(y_pred_rf3, y_futuro)
print(f"Ganancia de modelo RF: {ganancias_rf3}")

Ganancia de modelo RF: 245327500.0

Frente a los 208.010.000 de mi mejor árbol es algo sustancialmente mejor.

Igualmente usamos poquitos estimadores. Tan solo unos 100. Suficientes como para que la optimización no tarde una eternidad, pero es muy poco. Deberíamos sumar unos cuantos más.

In [ ]:
model_rf_1000 = RandomForestClassifier(
        n_estimators=1000,
        **study.best_params,
        max_samples=0.7,
        random_state=semillas[0],
        n_jobs=-1,
        oob_score=True
    )

model_rf_1000.fit(Xi, y)

filename_rf_1000 = modelos_path + 'exp_206_random_forest_model_1000.sav'
pickle.dump(model_rf, open(filename_rf_1000, 'wb'))

In [69]:
model_rf_1000_2 = RandomForestClassifier(
        n_estimators=1000,
        **study2.best_params,
        max_samples=0.7,
        random_state=semillas[0],
        n_jobs=-1,
        oob_score=True
    )

model_rf_1000_2.fit(Xi, y)

filename_rf_1000_2 = modelos_path + 'exp_71_random_forest_model_1000.sav'
pickle.dump(model_rf2, open(filename_rf_1000_2, 'wb'))

In [78]:
model_rf_1000_3 = RandomForestClassifier(
        n_estimators=1000,
        **study3.best_params,
        max_samples=0.7,
        random_state=semillas[0],
        n_jobs=-1,
        oob_score=True
    )

model_rf_1000_3.fit(Xi, y)

filename_rf_1000_3 = modelos_path + 'exp_91_random_forest_model_1000.sav'
pickle.dump(model_rf3, open(filename_rf_1000_3, 'wb'))

In [ ]:
model_rf_1000 = pickle.load(open(filename_rf_1000, 'rb'))
model_rf_1000

In [ ]:
model_rf_1000_2 = pickle.load(open(filename_rf_1000_2, 'rb'))
model_rf_1000_2

In [ ]:
model_rf_1000_3 = pickle.load(open(filename_rf_1000_3, 'rb'))
model_rf_1000_3

Veamos si sumar 10 veces más estimadores tuvo algún efecto

In [ ]:
y_pred_rf = model_rf_1000.predict_proba(Xif)
ganancias_rf = ganancia_prob(y_pred_rf, y_futuro)
print(f"Ganancia de modelo RF 1000: {ganancias_rf}")

Ganancia de modelo RF 1000: 253137500.0

Mejoró un poco! Cada peso vale.

Por último evaluamos cuales son las variables más importantes del modelo. ¿Habrá influido la imputación?

In [20]:
importances = model_rf.feature_importances_

features = X.columns
feat_importances = pd.DataFrame({'feature': features, 'importance': importances})
feat_importances = feat_importances.sort_values('importance', ascending=False)

feat_importances.head(25)

                       feature  importance
107               ctrx_quarter    0.219703
22              mcuentas_saldo    0.086965
33       mprestamos_personales    0.064014
18                mcaja_ahorro    0.059259
11             mpasivos_margen    0.042471
133                Visa_status    0.033728
99            ccajas_consultas    0.033291
16           mcuenta_corriente    0.032875
8         mrentabilidad_annual    0.032861
21    cdescubierto_preacordado    0.031803
28       mtarjeta_visa_consumo    0.024138
2               active_quarter    0.022014
111              Master_status    0.020803
32       cprestamos_personales    0.017540
7                mrentabilidad    0.015934
72   mcomisiones_mantenimiento    0.015228
29             ctarjeta_master    0.013599
12                  cproductos    0.012789
10             mactivos_margen    0.011314
127           Master_fechaalta    0.010630
51                cpayroll_trx    0.010395
98        ccajas_transacciones    0.010040
9                  mcomisiones    0.009952
74           mcomisiones_otras    0.009475
153           Visa_mpagominimo    0.009436

Vamos a hacer un par de experimentos, que pasa si sacamos la variable más importante?

In [21]:
most_important_feature = feat_importances.iloc[0]['feature']

X_df = pd.DataFrame(Xi, columns=X.columns)
X_futuro_df = pd.DataFrame(Xif, columns=X_futuro.columns)

X_no_best_feature = X_df.drop(columns=[most_important_feature])
X_futuro_no_best_feature = X_futuro_df.drop(columns=[most_important_feature])

model_rf_no_best_feature = RandomForestClassifier(
    n_estimators=100,
    **study.best_params,
    max_samples=0.7,
    random_state=semillas[0],
    n_jobs=-1,
    oob_score=True
)

print(f"Entrenando modelo RF sin '{most_important_feature}'...")
model_rf_no_best_feature.fit(X_no_best_feature, y)

y_pred_rf_no_best_feature = model_rf_no_best_feature.predict_proba(X_futuro_no_best_feature)

ganancia_rf_no_best_feature = ganancia_prob(y_pred_rf_no_best_feature, y_futuro)

print(f"Ganancia del modelo RF sin '{most_important_feature}': {ganancia_rf_no_best_feature}")
print(f"Ganancia del modelo RF original: {ganancias_rf}")

Entrenando modelo RF sin 'ctrx_quarter'...
Ganancia del modelo RF sin 'ctrx_quarter': 245767500.0
Ganancia del modelo RF original: 253137500.0

¿Qué paso? ¿Se ha derrumbado las ganancias frente a la ausencia del pilar de los árboles?

Una prueba más, que pasa si sumamos variables que son ruido puro.

In [22]:
X_df_from_Xi = pd.DataFrame(Xi, columns=X.columns)

np.random.seed(semilla)

random_features_train = pd.DataFrame({
    f'random_feature_{i}': np.random.rand(len(X_df_from_Xi)) for i in range(1, 6)
})

X_with_random_features = pd.concat([X_df_from_Xi, random_features_train], axis=1)

model_rf_new_features = RandomForestClassifier(
    n_estimators=100,
    **study.best_params,
    max_samples=0.7,
    random_state=semillas[0],
    n_jobs=-1,
    oob_score=True
)

model_rf_new_features.fit(X_with_random_features, y)

importances_new_features = model_rf_new_features.feature_importances_

features_new_features = X_with_random_features.columns
feat_importances_new_features = pd.DataFrame({'feature': features_new_features, 'importance': importances_new_features})
feat_importances_new_features = feat_importances_new_features.sort_values('importance', ascending=False)

display(feat_importances_new_features.head(25))

                       feature  importance
107               ctrx_quarter    0.228494
22              mcuentas_saldo    0.094135
33       mprestamos_personales    0.061438
11             mpasivos_margen    0.056584
18                mcaja_ahorro    0.041629
99            ccajas_consultas    0.035760
21    cdescubierto_preacordado    0.031391
8         mrentabilidad_annual    0.030823
16           mcuenta_corriente    0.027401
133                Visa_status    0.026903
28       mtarjeta_visa_consumo    0.021992
32       cprestamos_personales    0.019498
111              Master_status    0.019293
7                mrentabilidad    0.017626
2               active_quarter    0.013642
98        ccajas_transacciones    0.013191
29             ctarjeta_master    0.012714
10             mactivos_margen    0.012098
127           Master_fechaalta    0.011730
51                cpayroll_trx    0.010939
72   mcomisiones_mantenimiento    0.010928
12                  cproductos    0.010867
153           Visa_mpagominimo    0.008667
52                    mpayroll    0.008242
155           random_feature_1    0.007908

Y una más, cual es el área bajo la curva en train?

In [30]:
from sklearn.metrics import roc_auc_score

y_pred_rf_train = model_rf_1000.predict_proba(Xi)

ganancia_rf_train = ganancia_prob(y_pred_rf_train, y)
print(f"Ganancia en el conjunto de entrenamiento: {ganancia_rf_train}")
print(f"Ganancia en el conjunto de Mayo: {ganancias_rf}")

y_train_numeric = (y == 'BAJA+2').astype(int)
y_futuro_numeric = (y_futuro == 'BAJA+2').astype(int)

auc_train = roc_auc_score(y_train_numeric, y_pred_rf_train[:, 1])
print(f"Área bajo la curva (AUC) en el conjunto de entrenamiento: {auc_train}")

auc_mayo = roc_auc_score(y_futuro_numeric, y_pred_rf[:, 1])
print(f"Área bajo la curva (AUC) en el conjunto de Mayo: {auc_mayo}")

Ganancia en el conjunto de entrenamiento: 523600000.0
Ganancia en el conjunto de Mayo: 251570000.0
Área bajo la curva (AUC) en el conjunto de entrenamiento: 0.9606595035198221
Área bajo la curva (AUC) en el conjunto de Mayo: 0.8839194909782766

Cuanta diferencia entre conjuntos. Seguramente debemos descartar este algoritmo, ¿o no?

Pregunta:
* **¿Cómo sabe que un random forest es superior a otro?**
* **¿Cómo supera el random forest presentado?**

¿Cómo sabe que un random forest es superior a otro?

No alcanza con mirar el oob_score/ganancia OOB que usa Optuna en objective() (cell-16) para elegir hiperparámetros — el OOB es una proxy barata (evita hacer Monte Carlo CV) pero se calcula sobre la misma foto de Marzo, con la misma distribución de la que salió el modelo. La comparación real es:

Ganancia en un conjunto verdaderamente fuera de muestra y fuera de tiempo — acá Mayo (mes_test), que es justamente lo que hiciste en cell-31/36: comparar 251.570.000 (100 árboles) vs 253.137.500 (1000 árboles). Como el negocio es temporal (predecís el futuro con el pasado), la comparación válida es train (Marzo) vs. un mes posterior, no un split aleatorio del mismo mes.
Que la ganancia no dependa de una sola semilla — un RF puede "ganarle" a otro por azar en el bootstrap/random_state. Por eso el notebook arma una lista semillas de 50 valores: correr cada configuración candidata con varias semillas y comparar la ganancia promedio (o su dispersión) es más confiable que comparar un único run.
Que no haya overfitting severo — en cell-45 ves AUC 0.96 en train vs 0.88 en Mayo, y ganancia 523.6M en train vs 251.5M en Mayo. Un RF que "gana" en train pero se derrumba más en test no es mejor, aunque su métrica de training sea más alta.
¿Cómo supera el random forest presentado a lo anterior?

En cell-32 el notebook menciona que el mejor árbol individual (DecisionTreeClassifier) daba 208.010.000 de ganancia en Mayo. El RF con 100 árboles ya lo supera (251.570.000) y con 1000 sube un poco más (253.137.500). La razón no es que cada árbol individual del bosque sea mejor que el árbol óptimo — de hecho probablemente cada uno es peor, porque se entrena con bootstrap (menos datos efectivos) y con un subconjunto aleatorio de variables en cada split (max_features). La mejora viene de:

Bagging: promediar muchos árboles entrenados en distintos subconjuntos reduce la varianza (un árbol solo se sobreajusta a particularidades de la muestra; el promedio de 100-1000 árboles "cancela" ese ruido).
Decorrelación vía max_features: al forzar que cada split solo considere un subconjunto aleatorio de variables, los árboles del bosque se parecen menos entre sí, lo que hace que el promedio sea más efectivo que promediar árboles muy correlacionados (que aportarían poco más que un árbol solo).
Y el salto de 100 a 1000 estimadores (253.1M vs 251.5M) es chico porque el bagging tiene rendimientos decrecientes: la reducción de varianza por agregar más árboles converge rápido — pasado cierto punto, sumar árboles ya no decorrelaciona nada nuevo, solo promedia más finamente el mismo conjunto de patrones.

## Tarea:

* Mejore la parametrización del **rf**

1. Promediar la ganancia OOB sobre varias semillas (evita que Optuna "aprenda" hiperparámetros que solo funcionan bien con semillas[0]) El código original entrenaba un solo Random Forest por cada combinación de hiperparámetros que probaba Optuna, siempre con la misma semilla (semillas[0]). El problema: quizás esa combinación de hiperparámetros parece buena o mala un poco por casualidad, porque le tocó esa semilla en particular (la semilla determina qué filas caen en el bootstrap de cada árbol).

El bloque 1 en vez de eso, para cada combinación de hiperparámetros que Optuna quiere probar:

Entrena 3 Random Forest distintos (mismos hiperparámetros, pero 3 semillas diferentes).
Calcula la ganancia OOB de cada uno de los 3.
Devuelve el promedio de esas 3 ganancias como la "nota" de esa combinación de hiperparámetros.
Así, si una combinación de hiperparámetros da buenos resultados solo por azar con una semilla puntual, el promedio con las otras 2 semillas lo va a corregir. Es una nota más confiable, a costa de tardar 3 veces más por cada combinación que prueba Optuna.

¿En qué orden va todo?

El bloque 1 reemplaza el contenido de la celda 16 (ya lo dejé insertado ahí). No es un paso adicional, es la nueva versión de esa celda. De ahí en más, el notebook sigue exactamente el mismo orden que tenía antes:

Celda 16 (con el bloque 1 ya adentro) → define objective y crea el study
Celda 17 → study.optimize(...), ahora usando el objetivo de 3 semillas
Celdas 19-23 → gráficos de Optuna
Celda 25 en adelante → entrenar el modelo final con study.best_params