In [ ]:
pip install jupysql duckdb-engine ipykernel

In [3]:
import duckdb
import pandas as pd

%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False

%sql duckdb:///

dataset_path = "/Users/manuelmarasco/Library/CloudStorage/GoogleDrive-hola@manuelmarasco.com/Mi unidad/DMEyF/2026/notebooks/data/"
dataset_filename = "competencia_01_crudo.csv"

In [4]:
%%sql
create or replace table competencia_01_crudo as
select * replace (cast(numero_de_cliente as bigint) as numero_de_cliente)
from read_csv_auto("{{dataset_path + dataset_filename}}")

Empty DataFrame
Columns: [Success]
Index: []

In [5]:
%%sql
create or replace table competencia_01 as
with periodos as (select distinct foto_mes from competencia_01_crudo),
     clientes as (select distinct numero_de_cliente from competencia_01_crudo),
     todo as (select numero_de_cliente, foto_mes from clientes cross join periodos),

clasificador as (
select
    c.*,
    if(c.numero_de_cliente is null, 0, 1) as mes_0,
     case
       when lead(mes_0, 1) over (partition by t.numero_de_cliente order by t.foto_mes) = 0 then 'BAJA+1'
       when lead(mes_0, 1) over (partition by t.numero_de_cliente order by t.foto_mes) = 1 and lead(mes_0, 2) over (partition by t.numero_de_cliente order by t.foto_mes) = 0 then 'BAJA+2'
       when lead(mes_0, 1) over (partition by t.numero_de_cliente order by t.foto_mes) = 1 and lead(mes_0, 2) over (partition by t.numero_de_cliente order by t.foto_mes) = 1 then 'CONTINUA'
       else null
     end as clase_ternaria
from todo t
left join competencia_01_crudo c using (numero_de_cliente, foto_mes)
)

select * exclude (mes_0)
from clasificador
where mes_0 = 1
order by foto_mes

Empty DataFrame
Columns: [Success]
Index: []

In [6]:
%%sql
PIVOT competencia_01
on clase_ternaria
USING count(numero_de_cliente)
GROUP BY foto_mes

   foto_mes  BAJA+1  BAJA+2  CONTINUA
0    202103    1019     960    160921
1    202104     964    1139    161181
2    202105    1143     870    161755
3    202106     874    1098    162142
4    202107    1103       0         0
5    202108       0       0         0

In [10]:
%%sql
create or replace table historia as
select
    *
    -- Lags: valor del mes anterior y de dos meses antes
    , lag(ctrx_quarter, 1) over w as ctrx_quarter_lag1
    , lag(ctrx_quarter, 2) over w as ctrx_quarter_lag2
    -- Deltas: cuánto cambió respecto de 1 y 2 meses antes
    , ctrx_quarter - lag(ctrx_quarter, 1) over w as ctrx_quarter_delta1
    , ctrx_quarter - lag(ctrx_quarter, 2) over w as ctrx_quarter_delta2
    , mcuentas_saldo - lag(mcuentas_saldo, 1) over w as mcuentas_saldo_delta1
    , mcaja_ahorro - lag(mcaja_ahorro, 1) over w as mcaja_ahorro_delta1
    , mpasivos_margen - lag(mpasivos_margen, 1) over w as mpasivos_margen_delta1
    , mtarjeta_visa_consumo - lag(mtarjeta_visa_consumo, 1) over w as mtarjeta_visa_consumo_delta1
    , cproductos - lag(cproductos, 1) over w as cproductos_delta1
    , cproductos - lag(cproductos, 2) over w as cproductos_delta2
    , chomebanking_transacciones - lag(chomebanking_transacciones, 1) over w as chomebanking_transacciones_delta1
    , mprestamos_personales - lag(mprestamos_personales, 1) over w as mprestamos_personales_delta1
    -- Promedios de los últimos 3 meses (este y los 2 anteriores)
    , avg(ctrx_quarter) over w3 as ctrx_quarter_avg3
    , avg(coalesce(mtarjeta_visa_consumo, 0) + coalesce(mtarjeta_master_consumo, 0)) over w3 as consumo_tc_avg3
    -- Lags que usa la celda 6
    , lag(cpayroll_trx, 1) over w as cpayroll_trx_lag1
    , lag(cproductos, 1) over w as cproductos_lag1
    , lag(mprestamos_personales, 3) over w as mprestamos_personales_lag3
    , lag(cpayroll_trx, 2) over w as cpayroll_trx_lag2
    , lag(cpayroll_trx, 3) over w as cpayroll_trx_lag3
from competencia_01
window
    w  as (partition by numero_de_cliente order by foto_mes),
    w3 as (partition by numero_de_cliente order by foto_mes rows between 2 preceding and current row)

Empty DataFrame
Columns: [Success]
Index: []

In [12]:
%%sql
create or replace table competencia_01_fe as
with senales as (
    select
        *
        -- Desvinculación en curso (1 = la señal está presente este mes)
        , if(ctrx_quarter < 0.5 * ctrx_quarter_avg3, 1, 0) as cayo_actividad
        , if(coalesce(mtarjeta_visa_consumo, 0) + coalesce(mtarjeta_master_consumo, 0)
             < 0.5 * consumo_tc_avg3, 1, 0) as cayo_consumo_tc
        , if(cproductos < cproductos_lag1, 1, 0) as bajo_productos
        , if(cpayroll_trx_lag1 > 0 and coalesce(cpayroll_trx, 0) = 0, 1, 0) as dejo_de_cobrar_sueldo
        , if(coalesce(cpayroll_trx, 0) = 0
             and (cpayroll_trx_lag1 > 0 or cpayroll_trx_lag2 > 0 or cpayroll_trx_lag3 > 0), 1, 0)
          as dejo_de_cobrar_reciente
        -- Estado del vínculo
        , if(coalesce(cpayroll_trx, 0) > 0, 1, 0) as cobra_sueldo
        , if(cproductos <= 5, 1, 0) as pocos_productos
        -- El préstamo como ancla: el riesgo aparece cuando se termina
        , if(mprestamos_personales_lag3 > 0 and coalesce(mprestamos_personales, 0) = 0, 1, 0) as termino_prestamo
        , if(mprestamos_personales_lag3 > 0 and mprestamos_personales > 0
             and mprestamos_personales < 0.25 * mprestamos_personales_lag3, 1, 0) as prestamo_por_terminar
    from historia
)
select
    *
    -- Índice: cuántas señales de desvinculación tiene a la vez (0 a 4)
    , cayo_actividad + cayo_consumo_tc + bajo_productos + dejo_de_cobrar_reciente as indice_desvinculacion
from senales

Empty DataFrame
Columns: [Success]
Index: []

In [13]:
%%sql
select indice_desvinculacion, count(*) as clientes,
       round(avg(if(clase_ternaria = 'BAJA+2', 1, 0)) * 100, 2) as pct_baja2
from competencia_01_fe
where foto_mes between 202104 and 202106
group by 1 order by 1

   indice_desvinculacion  clientes  pct_baja2
0                      0    443123       0.54
1                      1     44190       1.32
2                      2      3333       3.36
3                      3       494       6.68
4                      4        26      11.54

In [14]:
data = %sql select * from competencia_01_fe where foto_mes in (202104, 202106, 202108)
data.shape

(492045, 184)

In [15]:
mes_train = 202104    # optimizar y entrenar el modelo de prueba
mes_test = 202106     # medir la ganancia (dos meses después, como z494)
mes_futuro = 202108   # entrega

ganancia_acierto = 1_072_500
costo_estimulo = 27_500

# Lo que NO entra al modelo
excluir = [
    'numero_de_cliente', 'foto_mes', 'clase_ternaria',                   # identificadores y clase
    'mpayroll', 'mpayroll2',                                             # monto del sueldo: no aporta y trae el aguinaldo
    'Visa_fultimo_cierre', 'Master_fultimo_cierre',                      # fechas: dependen del calendario (drift)
    'Visa_Finiciomora', 'Master_Finiciomora',
]
features = [c for c in data.columns if c not in excluir]

# Dos targets, para comparar (z601)
data['clase_binaria1'] = (data['clase_ternaria'] == 'BAJA+2').astype(int)                 # BAJA+2 vs resto
data['clase_binaria2'] = data['clase_ternaria'].isin(['BAJA+1', 'BAJA+2']).astype(int)   # BAJA+1 y BAJA+2 vs CONTINUA

train = data[data['foto_mes'] == mes_train]
test = data[data['foto_mes'] == mes_test]
futuro = data[data['foto_mes'] == mes_futuro]

print(len(features), 'variables')
print(train['clase_ternaria'].value_counts())

175 variables
clase_ternaria
CONTINUA    161181
BAJA+2        1139
BAJA+1         964
Name: count, dtype: int64

In [16]:
import numpy as np
import lightgbm as lgb
import optuna
from sklearn.model_selection import StratifiedShuffleSplit
from optuna.visualization import plot_optimization_history, plot_param_importances, plot_slice

/Users/manuelmarasco/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [18]:
semilla = 290497
np.random.seed(semilla)
semillas = np.random.choice(1000000, size=50, replace=False).tolist()

# Datos de abril en el formato de LightGBM. Target: BAJA+2 contra el resto (clase_binaria1)
X_train = train[features]
y_train_binaria = train['clase_binaria1']
train_data_lgb = lgb.Dataset(X_train, label=y_train_binaria, free_raw_data=False)

# 5 particiones 70/30 de abril, estratificadas por la clase
sss_opt = StratifiedShuffleSplit(n_splits=5, test_size=0.3, random_state=semillas[0])

# Ganancia como métrica de LightGBM: envía a los que tienen prob >= 0,025 (1/40)
def ganancia_prob_lgm(y_pred, data, prop=0.3):
    y_true = data.get_label()
    ganancia = np.where(y_true == 1, ganancia_acierto, 0) - np.where(y_true == 0, costo_estimulo, 0)
    return 'gan_prob', ganancia[y_pred >= 0.025].sum() / prop, True

def objective(trial):
    num_leaves = trial.suggest_int('num_leaves', 8, 100)
    learning_rate = trial.suggest_float('learning_rate', 0.005, 0.3)
    min_data_in_leaf = trial.suggest_int('min_data_in_leaf', 1, 1000)
    feature_fraction = trial.suggest_float('feature_fraction', 0.1, 1.0)
    bagging_fraction = trial.suggest_float('bagging_fraction', 0.1, 1.0)

    params = {
        'objective': 'binary',
        'metric': 'custom',
        'boosting_type': 'gbdt',
        'first_metric_only': True,
        'boost_from_average': True,
        'feature_pre_filter': False,
        'max_bin': 31,
        'num_leaves': num_leaves,
        'learning_rate': learning_rate,
        'min_data_in_leaf': min_data_in_leaf,
        'feature_fraction': feature_fraction,
        'bagging_fraction': bagging_fraction,
        'bagging_freq': 1,   # agregado: sin esto LightGBM ignora bagging_fraction
        'seed': semillas[0],
        'verbose': -1
    }

    cv_results = lgb.cv(
        params,
        train_data_lgb,
        num_boost_round=1000,
        callbacks=[lgb.early_stopping(stopping_rounds=int(50 + 5 / learning_rate), verbose=False)],
        feval=ganancia_prob_lgm,
        folds=sss_opt.split(X_train, y_train_binaria),
        seed=semillas[0]
    )

    max_gan = max(cv_results['valid gan_prob-mean'])
    best_iter = cv_results['valid gan_prob-mean'].index(max_gan) + 1
    trial.set_user_attr("best_iter", best_iter)   # guardamos cuántos árboles usó el mejor
    return max_gan

import os
os.makedirs('db', exist_ok=True)   # crea la carpeta si no existe

study = optuna.create_study(
    direction="maximize",
    study_name="mi_pipeline_binaria1",
    storage="sqlite:///" + os.path.abspath("db/optuna_mi_pipeline.db"),
    load_if_exists=True,
)

[I 2026-10-11 17:22:09,318] A new study created in RDB with name: mi_pipeline_binaria1

In [19]:
study.optimize(objective, n_trials=30)

[I 2026-10-11 17:23:29,646] Trial 0 finished with value: 479160000.0 and parameters: {'num_leaves': 55, 'learning_rate': 0.11970286353528098, 'min_data_in_leaf': 572, 'feature_fraction': 0.8178277052922529, 'bagging_fraction': 0.7863884504583578}. Best is trial 0 with value: 479160000.0.
[I 2026-10-11 17:23:35,623] Trial 1 finished with value: 430925000.0 and parameters: {'num_leaves': 21, 'learning_rate': 0.25664448146531194, 'min_data_in_leaf': 522, 'feature_fraction': 0.6568742199819212, 'bagging_fraction': 0.7275238126671791}. Best is trial 0 with value: 479160000.0.
[I 2026-10-11 17:23:51,094] Trial 2 finished with value: 320191666.6666667 and parameters: {'num_leaves': 46, 'learning_rate': 0.15475885299550574, 'min_data_in_leaf': 44, 'feature_fraction': 0.4742090336186196, 'bagging_fraction': 0.633679885505831}. Best is trial 0 with value: 479160000.0.
[I 2026-10-11 17:23:53,580] Trial 3 finished with value: 222566666.66666666 and parameters: {'num_leaves': 8, 'learning_rate': 0.2594992941930979, 'min_data_in_leaf': 41, 'feature_fraction': 0.22083616724871843, 'bagging_fraction': 0.1165342581172282}. Best is trial 0 with value: 479160000.0.
[I 2026-10-11 17:24:10,083] Trial 4 finished with value: 500940000.0 and parameters: {'num_leaves': 49, 'learning_rate': 0.07540054931096958, 'min_data_in_leaf': 818, 'feature_fraction': 0.36156405532588604, 'bagging_fraction': 0.6080170527326559}. Best is trial 4 with value: 500940000.0.
[I 2026-10-11 17:24:24,427] Trial 5 finished with value: 453585000.0 and parameters: {'num_leaves': 51, 'learning_rate': 0.12090209725021467, 'min_data_in_leaf': 346, 'feature_fraction': 0.39288072441001765, 'bagging_fraction': 0.5254420368798568}. Best is trial 4 with value: 500940000.0.
[I 2026-10-11 17:24:40,795] Trial 6 finished with value: 476941666.6666667 and parameters: {'num_leaves': 83, 'learning_rate': 0.10425767235848787, 'min_data_in_leaf': 545, 'feature_fraction': 0.6687094144204065, 'bagging_fraction': 0.9186698427562556}. Best is trial 4 with value: 500940000.0.
[I 2026-10-11 17:24:45,937] Trial 7 finished with value: 435160000.0 and parameters: {'num_leaves': 60, 'learning_rate': 0.23293372697966552, 'min_data_in_leaf': 721, 'feature_fraction': 0.4226839951862488, 'bagging_fraction': 0.16529344279651276}. Best is trial 4 with value: 500940000.0.
[I 2026-10-11 17:24:59,670] Trial 8 finished with value: 461725000.0 and parameters: {'num_leaves': 48, 'learning_rate': 0.13923955118110914, 'min_data_in_leaf': 474, 'feature_fraction': 0.2367468512860875, 'bagging_fraction': 0.9732588491552062}. Best is trial 4 with value: 500940000.0.
[I 2026-10-11 17:25:13,805] Trial 9 finished with value: 303545000.0 and parameters: {'num_leaves': 58, 'learning_rate': 0.21378069776856917, 'min_data_in_leaf': 84, 'feature_fraction': 0.23678360150382696, 'bagging_fraction': 0.47597858930080467}. Best is trial 4 with value: 500940000.0.
[I 2026-10-11 17:26:22,459] Trial 10 finished with value: 513150000.0 and parameters: {'num_leaves': 97, 'learning_rate': 0.007591413497635063, 'min_data_in_leaf': 899, 'feature_fraction': 0.9277090725974992, 'bagging_fraction': 0.33218954776857534}. Best is trial 10 with value: 513150000.0.
[I 2026-10-11 17:26:54,669] Trial 11 finished with value: 502003333.3333334 and parameters: {'num_leaves': 98, 'learning_rate': 0.023010362122852433, 'min_data_in_leaf': 1000, 'feature_fraction': 0.9860103680936769, 'bagging_fraction': 0.3119878683939502}. Best is trial 10 with value: 513150000.0.
[I 2026-10-11 17:27:56,705] Trial 12 finished with value: 508896666.6666667 and parameters: {'num_leaves': 100, 'learning_rate': 0.005940540619504258, 'min_data_in_leaf': 992, 'feature_fraction': 0.9298464387806766, 'bagging_fraction': 0.32027237247492624}. Best is trial 10 with value: 513150000.0.
[I 2026-10-11 17:28:56,465] Trial 13 finished with value: 507558333.3333333 and parameters: {'num_leaves': 99, 'learning_rate': 0.013862184713360412, 'min_data_in_leaf': 985, 'feature_fraction': 0.9879963145762747, 'bagging_fraction': 0.3415800444102492}. Best is trial 10 with value: 513150000.0.
[I 2026-10-11 17:29:13,360] Trial 14 finished with value: 494340000.0 and parameters: {'num_leaves': 80, 'learning_rate': 0.05221209906897028, 'min_data_in_leaf': 828, 'feature_fraction': 0.8397097000186327, 'bagging_fraction': 0.3039333573291118}. Best is trial 10 with value: 513150000.0.
[I 2026-10-11 17:30:38,660] Trial 15 finished with value: 513388333.3333333 and parameters: {'num_leaves': 87, 'learning_rate': 0.00788083184475592, 'min_data_in_leaf': 862, 'feature_fraction': 0.8317256174469636, 'bagging_fraction': 0.4159926841301224}. Best is trial 15 with value: 513388333.3333333.
[I 2026-10-11 17:31:03,025] Trial 16 finished with value: 495660000.0000001 and parameters: {'num_leaves': 81, 'learning_rate': 0.054075901210627705, 'min_data_in_leaf': 765, 'feature_fraction': 0.7369291621490027, 'bagging_fraction': 0.43261457305728407}. Best is trial 15 with value: 513388333.3333333.
[I 2026-10-11 17:31:28,447] Trial 17 finished with value: 504276666.6666667 and parameters: {'num_leaves': 71, 'learning_rate': 0.04889941747989023, 'min_data_in_leaf': 670, 'feature_fraction': 0.5918587791251558, 'bagging_fraction': 0.40713150426513756}. Best is trial 15 with value: 513388333.3333333.
[I 2026-10-11 17:31:38,342] Trial 18 finished with value: 488656666.6666667 and parameters: {'num_leaves': 89, 'learning_rate': 0.07840908384367537, 'min_data_in_leaf': 899, 'feature_fraction': 0.8552560952600067, 'bagging_fraction': 0.21126479580798901}. Best is trial 15 with value: 513388333.3333333.
[I 2026-10-11 17:32:05,343] Trial 19 finished with value: 498501666.6666667 and parameters: {'num_leaves': 70, 'learning_rate': 0.03362724926427284, 'min_data_in_leaf': 654, 'feature_fraction': 0.7561083985279644, 'bagging_fraction': 0.2274812913783692}. Best is trial 15 with value: 513388333.3333333.
[I 2026-10-11 17:32:17,243] Trial 20 finished with value: 470048333.3333334 and parameters: {'num_leaves': 89, 'learning_rate': 0.17986753471648215, 'min_data_in_leaf': 857, 'feature_fraction': 0.5567200887611057, 'bagging_fraction': 0.562628576207334}. Best is trial 15 with value: 513388333.3333333.
[I 2026-10-11 17:33:06,963] Trial 21 finished with value: 512178333.3333334 and parameters: {'num_leaves': 93, 'learning_rate': 0.01821690900219747, 'min_data_in_leaf': 912, 'feature_fraction': 0.9116316659602692, 'bagging_fraction': 0.36745783590506487}. Best is trial 15 with value: 513388333.3333333.
[I 2026-10-11 17:33:19,183] Trial 22 finished with value: 483376666.6666667 and parameters: {'num_leaves': 91, 'learning_rate': 0.08388430783881709, 'min_data_in_leaf': 890, 'feature_fraction': 0.9045404550771772, 'bagging_fraction': 0.3744558253573237}. Best is trial 15 with value: 513388333.3333333.
[I 2026-10-11 17:34:47,205] Trial 23 finished with value: 512838333.3333334 and parameters: {'num_leaves': 72, 'learning_rate': 0.007313181467079373, 'min_data_in_leaf': 909, 'feature_fraction': 0.7704012601218144, 'bagging_fraction': 0.46785042467649196}. Best is trial 15 with value: 513388333.3333333.
[I 2026-10-11 17:35:21,221] Trial 24 finished with value: 502993333.3333334 and parameters: {'num_leaves': 69, 'learning_rate': 0.04037886720633101, 'min_data_in_leaf': 768, 'feature_fraction': 0.7418173649797611, 'bagging_fraction': 0.444131006201061}. Best is trial 15 with value: 513388333.3333333.
[I 2026-10-11 17:37:10,081] Trial 25 finished with value: 513938333.3333334 and parameters: {'num_leaves': 76, 'learning_rate': 0.009414528604172152, 'min_data_in_leaf': 691, 'feature_fraction': 0.8075276247459833, 'bagging_fraction': 0.5141471765041344}. Best is trial 25 with value: 513938333.3333334.
[I 2026-10-11 17:37:30,847] Trial 26 finished with value: 492488333.3333334 and parameters: {'num_leaves': 79, 'learning_rate': 0.06973658044823929, 'min_data_in_leaf': 634, 'feature_fraction': 0.6812247071848286, 'bagging_fraction': 0.6814956225362577}. Best is trial 25 with value: 513938333.3333334.
[I 2026-10-11 17:37:36,347] Trial 27 finished with value: 426341666.6666667 and parameters: {'num_leaves': 37, 'learning_rate': 0.2965865076406111, 'min_data_in_leaf': 420, 'feature_fraction': 0.8382378706942198, 'bagging_fraction': 0.5381846590100688}. Best is trial 25 with value: 513938333.3333334.
[I 2026-10-11 17:38:07,963] Trial 28 finished with value: 488088333.3333334 and parameters: {'num_leaves': 65, 'learning_rate': 0.03449965552374461, 'min_data_in_leaf': 244, 'feature_fraction': 0.9197812391477758, 'bagging_fraction': 0.26327227292896294}. Best is trial 25 with value: 513938333.3333334.
[I 2026-10-11 17:38:30,849] Trial 29 finished with value: 494633333.3333334 and parameters: {'num_leaves': 86, 'learning_rate': 0.05756578724287953, 'min_data_in_leaf': 727, 'feature_fraction': 0.8014993314216086, 'bagging_fraction': 0.5017448793555076}. Best is trial 25 with value: 513938333.3333334.

In [20]:
print('Mejor ganancia CV:', study.best_value)
print('Mejores parámetros:', study.best_params)
print('Árboles:', study.best_trial.user_attrs['best_iter'])
plot_optimization_history(study)

Mejor ganancia CV: 513938333.3333334
Mejores parámetros: {'num_leaves': 76, 'learning_rate': 0.009414528604172152, 'min_data_in_leaf': 691, 'feature_fraction': 0.8075276247459833, 'bagging_fraction': 0.5141471765041344}
Árboles: 655

In [21]:
def ganancia_umbral(prob, clase_ternaria, umbral=0.025, prop=1):
    """Ganancia de enviar a todos los que superan el umbral (como en z601)."""
    g = np.where(clase_ternaria == 'BAJA+2', ganancia_acierto, -costo_estimulo)
    return g[prob >= umbral].sum() / prop

params = {
    'objective': 'binary', 'boosting_type': 'gbdt', 'first_metric_only': True,
    'boost_from_average': True, 'feature_pre_filter': False, 'max_bin': 31,
    'bagging_freq': 1, 'seed': semillas[0], 'verbose': -1,
    **study.best_params,
}
best_iter = study.best_trial.user_attrs['best_iter']
modelo = lgb.train(params, lgb.Dataset(X_train, label=y_train_binaria), num_boost_round=best_iter)

gan_abril = ganancia_umbral(modelo.predict(X_train), train['clase_ternaria'].values)
gan_cv = study.best_value
gan_junio = ganancia_umbral(modelo.predict(test[features]), test['clase_ternaria'].values)

print(f"Abril completo (visto):  {gan_abril:>15,.0f}")
print(f"CV en abril (Optuna):    {gan_cv:>15,.0f}")
print(f"Junio (nunca visto):     {gan_junio:>15,.0f}")

Abril completo (visto):      993,987,500
CV en abril (Optuna):        513,938,333
Junio (nunca visto):         341,770,000

In [22]:
n_semillas = 5
cortes = np.arange(4000, 19001, 500)   # cantidades de envíos a evaluar (z494)

dtrain = lgb.Dataset(X_train, label=y_train_binaria)
predicciones = []
filas = []

mis_semillas = [100129, 100183, 100151, 500041, 900007]
for seed in mis_semillas:
    params_seed = {**params, 'seed': seed}
    m = lgb.train(params_seed, dtrain, num_boost_round=best_iter)
    pred = m.predict(test[features])
    predicciones.append(pred)

    # Curva de ganancia de esta semilla: ordeno de mayor a menor prob y acumulo
    orden = np.argsort(pred)[::-1]
    gan = np.where(test['clase_ternaria'].values[orden] == 'BAJA+2', ganancia_acierto, -costo_estimulo)
    gan_acum = np.cumsum(gan)
    for corte in cortes:
        filas.append({'seed': seed, 'envios': corte, 'ganancia': gan_acum[corte - 1]})

# Semillerío: promedio de las probabilidades de las 5 semillas
prob_semillerio = np.mean(predicciones, axis=0)
orden = np.argsort(prob_semillerio)[::-1]
gan = np.where(test['clase_ternaria'].values[orden] == 'BAJA+2', ganancia_acierto, -costo_estimulo)
gan_acum_semillerio = np.cumsum(gan)

tabla = pd.DataFrame(filas).groupby('envios')['ganancia'].agg(['mean', 'std'])
tabla['semillerio'] = gan_acum_semillerio[cortes - 1]
tabla = (tabla / 1e6).round(1)   # en millones
print(tabla)
print('Mejor corte del semillerío:', tabla['semillerio'].idxmax(), 'envíos ->', tabla['semillerio'].max(), 'M')

         mean  std  semillerio
envios
4000    265.8  3.7       270.6
4500    283.9  4.6       285.4
5000    297.4  2.9       300.3
5500    305.9  6.1       306.4
6000    308.7  4.4       316.8
6500    317.8  1.7       317.4
7000    323.8  4.1       326.7
7500    327.2  5.2       331.6
8000    332.4  5.1       344.3
8500    342.6  2.6       344.8
9000    355.1  3.7       354.2
9500    360.0  6.7       361.4
10000   368.7  7.4       366.3
10500   374.1  3.9       379.0
11000   375.3  6.2       378.4
11500   376.5  5.7       374.6
12000   376.6  3.4       380.6
12500   375.4  4.5       374.6
13000   375.1  3.4       379.5
13500   374.1  5.0       377.8
14000   377.3  4.6       376.2
14500   374.3  4.5       371.2
15000   370.9  5.3       372.9
15500   366.8  5.0       372.4
16000   365.9  7.2       370.7
16500   363.6  5.2       371.2
17000   357.9  3.9       364.1
17500   353.4  6.6       357.0
18000   350.0  9.5       353.1
18500   344.4  9.7       349.2
19000   339.2  6.2       339.9
Mejor corte del semillerío: 12000 envíos -> 380.6 M

In [23]:
from scipy.stats import rankdata

# Mismo modelo, target BAJA+1 + BAJA+2 (clase_binaria2)
dtrain2 = lgb.Dataset(X_train, label=train['clase_binaria2'])
predicciones2 = []
for seed in mis_semillas:
    m = lgb.train({**params, 'seed': seed}, dtrain2, num_boost_round=best_iter)
    predicciones2.append(m.predict(test[features]))
prob_semillerio2 = np.mean(predicciones2, axis=0)

def curva(prob):
    """Ganancia acumulada en junio, ordenando de mayor a menor probabilidad."""
    orden = np.argsort(prob)[::-1]
    gan = np.where(test['clase_ternaria'].values[orden] == 'BAJA+2', ganancia_acierto, -costo_estimulo)
    return np.cumsum(gan)[cortes - 1]

# Ensamble: promedio de los RANKINGS de los dos modelos (no de las probabilidades)
ensamble = (rankdata(prob_semillerio) + rankdata(prob_semillerio2)) / 2

comparacion = pd.DataFrame({
    'binaria1 (BAJA+2)': curva(prob_semillerio),
    'binaria2 (BAJA+1+2)': curva(prob_semillerio2),
    'ensamble': curva(ensamble),
}, index=cortes) / 1e6
print(comparacion.round(1))
print('\nMejor de cada uno:')
print(pd.DataFrame({'envios': comparacion.idxmax(), 'ganancia_M': comparacion.max().round(1)}))

       binaria1 (BAJA+2)  binaria2 (BAJA+1+2)  ensamble
4000               270.6                287.1     277.2
4500               285.4                310.8     300.8
5000               300.3                317.9     312.4
5500               306.4                324.0     317.4
6000               316.8                336.6     324.5
6500               317.4                346.0     339.4
7000               326.7                348.7     345.4
7500               331.6                358.0     347.0
8000               344.3                364.1     355.3
8500               344.8                371.2     364.6
9000               354.2                370.7     371.8
9500               361.4                375.6     382.2
10000              366.3                381.7     387.2
10500              379.0                383.4     390.0
11000              378.4                392.7     391.6
11500              374.6                399.8     393.2
12000              380.6                398.2     393.8
12500              374.6                399.8     393.2
13000              379.5                409.2     398.2
13500              377.8                408.6     403.2
14000              376.2                408.1     401.5
14500              371.2                412.0     399.8
15000              372.9                411.4     393.8
15500              372.4                402.0     391.0
16000              370.7                394.9     387.2
16500              371.2                391.0     381.2
17000              364.1                389.4     382.8
17500              357.0                387.8     375.6
18000              353.1                379.5     372.9
18500              349.2                373.4     370.2
19000              339.9                366.3     368.5

Mejor de cada uno:
                     envios  ganancia_M
binaria1 (BAJA+2)     12000       380.6
binaria2 (BAJA+1+2)   14500       412.0
ensamble              13500       403.2

In [24]:
k = 14500   # mejor corte en junio (centro de la meseta 13.000-15.000)

# Entrenar con junio (target ganador: BAJA+1 + BAJA+2)
dtrain_final = lgb.Dataset(test[features], label=test['clase_binaria2'])
predicciones_futuro = []
for seed in mis_semillas:
    m = lgb.train({**params, 'seed': seed}, dtrain_final, num_boost_round=best_iter)
    predicciones_futuro.append(m.predict(futuro[features]))
prob_futuro = np.mean(predicciones_futuro, axis=0)   # semillerío

# Los k clientes de agosto con mayor probabilidad
orden = np.argsort(prob_futuro)[::-1]
elegidos = futuro['numero_de_cliente'].values[orden][:k].astype('int64')

import os
os.makedirs('entregas', exist_ok=True)
archivo = 'entregas/mi_pipeline_b2_k14500.csv'
pd.Series(elegidos).to_csv(archivo, index=False, header=False)
print(archivo, '->', len(elegidos), 'ids')
print(open(archivo).read()[:60])   # control: primeros ids, sin encabezado ni decimales

entregas/mi_pipeline_b2_k14500.csv -> 14500 ids
42425357
31959546
44781626
45696840
57157011
42520550
575325

Undersampling

In [ ]:
"""UNDERSAMPLING = 0.1
rng = np.random.default_rng(semilla)
mascara_us = (rng.random(len(train)) < UNDERSAMPLING) | (train['clase_ternaria'] != 'CONTINUA')
train_us = train[mascara_us]
print(len(train_us), 'filas;', train_us['clase_ternaria'].value_counts().to_dict())

# Pesos casi iguales a 1: no cambian el entrenamiento, pero le dicen a la métrica quién es BAJA+2
pesos = np.select([train_us['clase_ternaria'] == 'BAJA+2', train_us['clase_ternaria'] == 'BAJA+1'],
                  [1.00002, 1.00001], default=1.0)
dtrain_us = lgb.Dataset(train_us[features], label=train_us['clase_binaria2'],
                        weight=pesos, free_raw_data=False)

def ganancia_max_lgb(y_pred, data):
    """Mejor ganancia posible eligiendo el corte, en el fold de validación."""
    w = data.get_weight()
    g = np.where(w > 1.000015, ganancia_acierto,                 # BAJA+2: gana
         np.where(w > 1.000005, -costo_estimulo,                 # BAJA+1: cuesta
                  -costo_estimulo / UNDERSAMPLING))              # CONTINUA: cuesta x10 (representa a 10)
    orden = np.argsort(-y_pred)
    return 'gan_max', np.cumsum(g[orden]).max() * 5, True       # x5: de un fold a todo abril

def objective_us(trial):
    lr = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
    p = {
        'objective': 'binary', 'metric': 'None', 'boosting_type': 'gbdt',
        'feature_pre_filter': False, 'max_bin': 31, 'verbose': -1, 'seed': semillas[0],
        'learning_rate': lr,
        'num_leaves': trial.suggest_int('num_leaves', 8, 2048, log=True),
        'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 1, 8000, log=True),
        'feature_fraction': trial.suggest_float('feature_fraction', 0.1, 1.0),
    }
    cv = lgb.cv(p, dtrain_us, num_boost_round=5000, nfold=5, stratified=True, seed=semillas[0],
                feval=ganancia_max_lgb,
                callbacks=[lgb.early_stopping(int(50 + 5 / lr), verbose=False)])
    curva_cv = cv['valid gan_max-mean']
    trial.set_user_attr('best_iter', int(np.argmax(curva_cv)) + 1)
    return max(curva_cv)

study_us = optuna.create_study(direction='maximize', study_name='mi_pipeline_us_ganancia',
                               storage='sqlite:///' + os.path.abspath('db/optuna_mi_pipeline.db'),
                               load_if_exists=True)
study_us.optimize(objective_us, n_trials=100)
print('Mejor ganancia CV:', study_us.best_value, study_us.best_params,
      'árboles:', study_us.best_trial.user_attrs['best_iter'])"""

In [27]:
from sklearn.model_selection import StratifiedKFold

UNDERSAMPLING = 0.1
rng = np.random.default_rng(semilla)
mascara_us = (rng.random(len(train)) < UNDERSAMPLING) | (train['clase_ternaria'] != 'CONTINUA')
train_us = train[mascara_us]
print(len(train_us), 'filas;', train_us['clase_ternaria'].value_counts().to_dict())

X_us = train_us[features]
y_us = train_us['clase_binaria2'].values
# Ganancia de cada cliente: BAJA+2 gana; BAJA+1 cuesta; CONTINUA cuesta x10 (cada uno representa a 10)
g_us = np.where(train_us['clase_ternaria'] == 'BAJA+2', ganancia_acierto,
       np.where(train_us['clase_ternaria'] == 'BAJA+1', -costo_estimulo,
                -costo_estimulo / UNDERSAMPLING)).astype(float)

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=semillas[0])
folds = list(skf.split(X_us, y_us))

def objective_us(trial):
    p = {
        'objective': 'binary', 'boosting_type': 'gbdt', 'feature_pre_filter': False,
        'max_bin': 31, 'verbose': -1, 'seed': semillas[0],
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 8, 256, log=True),
        'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 20, 2000, log=True),
        'feature_fraction': trial.suggest_float('feature_fraction', 0.1, 1.0),
    }
    n_arboles = trial.suggest_int('num_iterations', 50, 1500, log=True)   # como en z494
    ganancias = []
    for tr, va in folds:
        m = lgb.train(p, lgb.Dataset(X_us.iloc[tr], label=y_us[tr]), num_boost_round=n_arboles)
        pred = m.predict(X_us.iloc[va])
        ganancias.append(np.cumsum(g_us[va][np.argsort(-pred)]).max() * 5)   # mejor corte del fold
    return float(np.mean(ganancias))

study_us = optuna.create_study(direction='maximize', study_name='mi_pipeline_us_ganancia_v3',
                               storage='sqlite:///' + os.path.abspath('db/optuna_mi_pipeline.db'),
                               load_if_exists=True)
study_us.optimize(objective_us, n_trials=100)
print('Mejor ganancia CV:', study_us.best_value, study_us.best_params)

[I 2026-10-11 18:21:38,115] A new study created in RDB with name: mi_pipeline_us_ganancia_v3

18212 filas; {'CONTINUA': 16109, 'BAJA+2': 1139, 'BAJA+1': 964}

[I 2026-10-11 18:21:57,995] Trial 0 finished with value: 541612500.0 and parameters: {'learning_rate': 0.05506155669632382, 'num_leaves': 12, 'min_data_in_leaf': 42, 'feature_fraction': 0.1906976250107658, 'num_iterations': 898}. Best is trial 0 with value: 541612500.0.
[I 2026-10-11 18:22:12,881] Trial 1 finished with value: 547992500.0 and parameters: {'learning_rate': 0.029148776616102243, 'num_leaves': 97, 'min_data_in_leaf': 21, 'feature_fraction': 0.7637230740762034, 'num_iterations': 113}. Best is trial 1 with value: 547992500.0.
[I 2026-10-11 18:22:17,154] Trial 2 finished with value: 536140000.0 and parameters: {'learning_rate': 0.014369670712168471, 'num_leaves': 16, 'min_data_in_leaf': 168, 'feature_fraction': 0.36497998839431384, 'num_iterations': 139}. Best is trial 1 with value: 547992500.0.
[I 2026-10-11 18:22:28,805] Trial 3 finished with value: 546947500.0 and parameters: {'learning_rate': 0.013127107135176728, 'num_leaves': 80, 'min_data_in_leaf': 30, 'feature_fraction': 0.7572575773811117, 'num_iterations': 110}. Best is trial 1 with value: 547992500.0.
[I 2026-10-11 18:22:35,921] Trial 4 finished with value: 548872500.0 and parameters: {'learning_rate': 0.14112760681594727, 'num_leaves': 77, 'min_data_in_leaf': 77, 'feature_fraction': 0.3770427624305539, 'num_iterations': 60}. Best is trial 4 with value: 548872500.0.
[I 2026-10-11 18:23:56,785] Trial 5 finished with value: 540925000.0 and parameters: {'learning_rate': 0.12815267812904266, 'num_leaves': 144, 'min_data_in_leaf': 70, 'feature_fraction': 0.6370054712037181, 'num_iterations': 606}. Best is trial 4 with value: 548872500.0.
[I 2026-10-11 18:24:15,433] Trial 6 finished with value: 519392500.0 and parameters: {'learning_rate': 0.10104754623428261, 'num_leaves': 15, 'min_data_in_leaf': 483, 'feature_fraction': 0.31235330120236426, 'num_iterations': 750}. Best is trial 4 with value: 548872500.0.
[I 2026-10-11 18:24:55,478] Trial 7 finished with value: 547085000.0 and parameters: {'learning_rate': 0.01943805228849077, 'num_leaves': 31, 'min_data_in_leaf': 239, 'feature_fraction': 0.604871084323882, 'num_iterations': 951}. Best is trial 4 with value: 548872500.0.
[I 2026-10-11 18:25:04,949] Trial 8 finished with value: 524287500.0 and parameters: {'learning_rate': 0.22138943361276028, 'num_leaves': 18, 'min_data_in_leaf': 1148, 'feature_fraction': 0.14638951270607065, 'num_iterations': 569}. Best is trial 4 with value: 548872500.0.
[I 2026-10-11 18:29:42,313] Trial 9 finished with value: 547277500.0 and parameters: {'learning_rate': 0.024798326305265975, 'num_leaves': 170, 'min_data_in_leaf': 25, 'feature_fraction': 0.757085084874786, 'num_iterations': 1276}. Best is trial 4 with value: 548872500.0.
[I 2026-10-11 18:29:43,222] Trial 10 finished with value: 509575000.0 and parameters: {'learning_rate': 0.05075657916362718, 'num_leaves': 53, 'min_data_in_leaf': 1272, 'feature_fraction': 0.9567421660696058, 'num_iterations': 57}. Best is trial 4 with value: 548872500.0.
[I 2026-10-11 18:29:49,978] Trial 11 finished with value: 507347500.0 and parameters: {'learning_rate': 0.29562614042757507, 'num_leaves': 80, 'min_data_in_leaf': 81, 'feature_fraction': 0.45808436410719594, 'num_iterations': 54}. Best is trial 4 with value: 548872500.0.
[I 2026-10-11 18:30:30,248] Trial 12 finished with value: 547772500.0 and parameters: {'learning_rate': 0.033393873083701085, 'num_leaves': 230, 'min_data_in_leaf': 21, 'feature_fraction': 0.9910838491178842, 'num_iterations': 143}. Best is trial 4 with value: 548872500.0.
[I 2026-10-11 18:31:01,263] Trial 13 finished with value: 544225000.0 and parameters: {'learning_rate': 0.1094566956192793, 'num_leaves': 91, 'min_data_in_leaf': 105, 'feature_fraction': 0.5902280576016408, 'num_iterations': 258}. Best is trial 4 with value: 548872500.0.
[I 2026-10-11 18:31:05,164] Trial 14 finished with value: 552227500.0 and parameters: {'learning_rate': 0.051169140423026914, 'num_leaves': 31, 'min_data_in_leaf': 49, 'feature_fraction': 0.8410784948640015, 'num_iterations': 86}. Best is trial 14 with value: 552227500.0.
[I 2026-10-11 18:31:09,741] Trial 15 finished with value: 569085000.0 and parameters: {'learning_rate': 0.06913650068425481, 'num_leaves': 35, 'min_data_in_leaf': 53, 'feature_fraction': 0.47906319306758594, 'num_iterations': 76}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:31:18,853] Trial 16 finished with value: 546645000.0 and parameters: {'learning_rate': 0.06491533090177388, 'num_leaves': 27, 'min_data_in_leaf': 47, 'feature_fraction': 0.8598206573434113, 'num_iterations': 247}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:31:23,521] Trial 17 finished with value: 559927500.0 and parameters: {'learning_rate': 0.0711093883367361, 'num_leaves': 36, 'min_data_in_leaf': 170, 'feature_fraction': 0.49413878887572943, 'num_iterations': 81}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:31:27,435] Trial 18 finished with value: 564327500.0 and parameters: {'learning_rate': 0.07523469215154249, 'num_leaves': 9, 'min_data_in_leaf': 315, 'feature_fraction': 0.5047447647612409, 'num_iterations': 219}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:31:32,814] Trial 19 finished with value: 556490000.0 and parameters: {'learning_rate': 0.037360853771006154, 'num_leaves': 9, 'min_data_in_leaf': 633, 'feature_fraction': 0.2814821781937451, 'num_iterations': 314}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:31:37,554] Trial 20 finished with value: 536470000.0 and parameters: {'learning_rate': 0.0832559938336834, 'num_leaves': 8, 'min_data_in_leaf': 1973, 'feature_fraction': 0.47536007335050656, 'num_iterations': 388}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:31:48,574] Trial 21 finished with value: 544582500.0 and parameters: {'learning_rate': 0.07885844936950477, 'num_leaves': 47, 'min_data_in_leaf': 279, 'feature_fraction': 0.49472157358565183, 'num_iterations': 187}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:31:54,057] Trial 22 finished with value: 550082500.0 and parameters: {'learning_rate': 0.07541250900304759, 'num_leaves': 48, 'min_data_in_leaf': 150, 'feature_fraction': 0.5841607501657975, 'num_iterations': 81}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:31:56,975] Trial 23 finished with value: 544637500.0 and parameters: {'learning_rate': 0.1722425478561547, 'num_leaves': 22, 'min_data_in_leaf': 401, 'feature_fraction': 0.5154302377772747, 'num_iterations': 79}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:32:08,520] Trial 24 finished with value: 554317500.0 and parameters: {'learning_rate': 0.0412115815878855, 'num_leaves': 41, 'min_data_in_leaf': 205, 'feature_fraction': 0.4054842562535065, 'num_iterations': 189}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:32:10,820] Trial 25 finished with value: 549285000.0 and parameters: {'learning_rate': 0.09548990822860837, 'num_leaves': 11, 'min_data_in_leaf': 118, 'feature_fraction': 0.26943847865918874, 'num_iterations': 103}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:32:17,231] Trial 26 finished with value: 547992500.0 and parameters: {'learning_rate': 0.06332482785004578, 'num_leaves': 62, 'min_data_in_leaf': 352, 'feature_fraction': 0.6940524004677431, 'num_iterations': 161}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:32:19,190] Trial 27 finished with value: 539385000.0 and parameters: {'learning_rate': 0.16423286333089496, 'num_leaves': 23, 'min_data_in_leaf': 711, 'feature_fraction': 0.5575164284290259, 'num_iterations': 71}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:32:42,425] Trial 28 finished with value: 552145000.0 and parameters: {'learning_rate': 0.04426630647039848, 'num_leaves': 37, 'min_data_in_leaf': 113, 'feature_fraction': 0.41590627001631764, 'num_iterations': 398}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:32:43,783] Trial 29 finished with value: 544720000.0 and parameters: {'learning_rate': 0.0608161573289266, 'num_leaves': 12, 'min_data_in_leaf': 39, 'feature_fraction': 0.23876302412467354, 'num_iterations': 50}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:32:53,838] Trial 30 finished with value: 532895000.0 and parameters: {'learning_rate': 0.010170869669415059, 'num_leaves': 123, 'min_data_in_leaf': 304, 'feature_fraction': 0.6612474008066621, 'num_iterations': 218}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:33:00,632] Trial 31 finished with value: 552337500.0 and parameters: {'learning_rate': 0.03822543673963468, 'num_leaves': 11, 'min_data_in_leaf': 615, 'feature_fraction': 0.32252319624535136, 'num_iterations': 342}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:33:05,439] Trial 32 finished with value: 540182500.0 and parameters: {'learning_rate': 0.025451769846955574, 'num_leaves': 8, 'min_data_in_leaf': 797, 'feature_fraction': 0.20861386510985735, 'num_iterations': 308}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:33:07,341] Trial 33 finished with value: 504075000.0 and parameters: {'learning_rate': 0.03165738151497717, 'num_leaves': 9, 'min_data_in_leaf': 434, 'feature_fraction': 0.1353093809744913, 'num_iterations': 101}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:33:10,983] Trial 34 finished with value: 563667500.0 and parameters: {'learning_rate': 0.07261986018990166, 'num_leaves': 15, 'min_data_in_leaf': 178, 'feature_fraction': 0.5222498262414612, 'num_iterations': 128}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:33:14,514] Trial 35 finished with value: 548322500.0 and parameters: {'learning_rate': 0.11821853828857812, 'num_leaves': 16, 'min_data_in_leaf': 170, 'feature_fraction': 0.5265623428880599, 'num_iterations': 119}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:33:17,697] Trial 36 finished with value: 561000000.0 and parameters: {'learning_rate': 0.08974175092643515, 'num_leaves': 13, 'min_data_in_leaf': 59, 'feature_fraction': 0.4405827473604113, 'num_iterations': 124}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:33:21,019] Trial 37 finished with value: 559817500.0 and parameters: {'learning_rate': 0.08893594379446901, 'num_leaves': 13, 'min_data_in_leaf': 61, 'feature_fraction': 0.4351938391554653, 'num_iterations': 130}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:33:26,781] Trial 38 finished with value: 537982500.0 and parameters: {'learning_rate': 0.14709448063683025, 'num_leaves': 20, 'min_data_in_leaf': 90, 'feature_fraction': 0.3790718251094862, 'num_iterations': 163}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:33:28,607] Trial 39 finished with value: 548570000.0 and parameters: {'learning_rate': 0.10159743807186053, 'num_leaves': 13, 'min_data_in_leaf': 36, 'feature_fraction': 0.3595808324316643, 'num_iterations': 66}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:33:30,847] Trial 40 finished with value: 554647500.0 and parameters: {'learning_rate': 0.053954759314336125, 'num_leaves': 14, 'min_data_in_leaf': 61, 'feature_fraction': 0.6846248638160803, 'num_iterations': 99}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:33:33,896] Trial 41 finished with value: 562485000.0 and parameters: {'learning_rate': 0.07263752288608837, 'num_leaves': 18, 'min_data_in_leaf': 164, 'feature_fraction': 0.5399747999438697, 'num_iterations': 90}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:33:38,176] Trial 42 finished with value: 558277500.0 and parameters: {'learning_rate': 0.0861664575233183, 'num_leaves': 18, 'min_data_in_leaf': 221, 'feature_fraction': 0.5628613031129799, 'num_iterations': 138}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:33:40,227] Trial 43 finished with value: 554922500.0 and parameters: {'learning_rate': 0.12682298294201164, 'num_leaves': 10, 'min_data_in_leaf': 140, 'feature_fraction': 0.5396596144773748, 'num_iterations': 96}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:33:45,609] Trial 44 finished with value: 556407500.0 and parameters: {'learning_rate': 0.07308754528637573, 'num_leaves': 25, 'min_data_in_leaf': 32, 'feature_fraction': 0.4582912726081794, 'num_iterations': 121}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:33:49,709] Trial 45 finished with value: 556957500.0 and parameters: {'learning_rate': 0.04642412566734753, 'num_leaves': 19, 'min_data_in_leaf': 259, 'feature_fraction': 0.623598250448519, 'num_iterations': 148}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:33:51,974] Trial 46 finished with value: 550522500.0 and parameters: {'learning_rate': 0.059868804959223816, 'num_leaves': 16, 'min_data_in_leaf': 65, 'feature_fraction': 0.3548364691447742, 'num_iterations': 70}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:34:00,011] Trial 47 finished with value: 534352500.0 and parameters: {'learning_rate': 0.1075253225592556, 'num_leaves': 30, 'min_data_in_leaf': 91, 'feature_fraction': 0.7297794122249811, 'num_iterations': 197}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:34:03,411] Trial 48 finished with value: 557012500.0 and parameters: {'learning_rate': 0.07071865006174217, 'num_leaves': 15, 'min_data_in_leaf': 29, 'feature_fraction': 0.44104354420443387, 'num_iterations': 116}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:34:47,964] Trial 49 finished with value: 543922500.0 and parameters: {'learning_rate': 0.05702539616670801, 'num_leaves': 62, 'min_data_in_leaf': 50, 'feature_fraction': 0.6270734272652801, 'num_iterations': 530}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:34:49,956] Trial 50 finished with value: 546452500.0 and parameters: {'learning_rate': 0.1928535727666597, 'num_leaves': 11, 'min_data_in_leaf': 509, 'feature_fraction': 0.4968540958124242, 'num_iterations': 90}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:34:53,540] Trial 51 finished with value: 560587500.0 and parameters: {'learning_rate': 0.07015854900564504, 'num_leaves': 36, 'min_data_in_leaf': 185, 'feature_fraction': 0.48016895227317624, 'num_iterations': 62}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:34:56,242] Trial 52 finished with value: 561852500.0 and parameters: {'learning_rate': 0.09493823280079305, 'num_leaves': 27, 'min_data_in_leaf': 198, 'feature_fraction': 0.5858346773041512, 'num_iterations': 63}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:34:58,520] Trial 53 finished with value: 561357500.0 and parameters: {'learning_rate': 0.09479903067760015, 'num_leaves': 25, 'min_data_in_leaf': 222, 'feature_fraction': 0.6011607550523853, 'num_iterations': 58}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:35:01,055] Trial 54 finished with value: 542960000.0 and parameters: {'learning_rate': 0.11497788763348793, 'num_leaves': 29, 'min_data_in_leaf': 320, 'feature_fraction': 0.5852376001035071, 'num_iterations': 58}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:35:03,718] Trial 55 finished with value: 549890000.0 and parameters: {'learning_rate': 0.09814927145378421, 'num_leaves': 24, 'min_data_in_leaf': 225, 'feature_fraction': 0.6559132321138442, 'num_iterations': 77}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:35:05,806] Trial 56 finished with value: 551512500.0 and parameters: {'learning_rate': 0.1438720067869122, 'num_leaves': 20, 'min_data_in_leaf': 148, 'feature_fraction': 0.5534377236484875, 'num_iterations': 55}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:35:08,474] Trial 57 finished with value: 557287500.0 and parameters: {'learning_rate': 0.049978108908859335, 'num_leaves': 27, 'min_data_in_leaf': 137, 'feature_fraction': 0.7885495670349105, 'num_iterations': 67}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:35:10,940] Trial 58 finished with value: 553025000.0 and parameters: {'learning_rate': 0.1304409567459592, 'num_leaves': 42, 'min_data_in_leaf': 347, 'feature_fraction': 0.5908606297547409, 'num_iterations': 51}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:35:15,741] Trial 59 finished with value: 558250000.0 and parameters: {'learning_rate': 0.0784118596941548, 'num_leaves': 34, 'min_data_in_leaf': 198, 'feature_fraction': 0.5237166385905717, 'num_iterations': 88}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:35:18,573] Trial 60 finished with value: 555280000.0 and parameters: {'learning_rate': 0.06450262735621198, 'num_leaves': 26, 'min_data_in_leaf': 271, 'feature_fraction': 0.6149283822993121, 'num_iterations': 75}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:35:23,068] Trial 61 finished with value: 549257500.0 and parameters: {'learning_rate': 0.09307150995547223, 'num_leaves': 22, 'min_data_in_leaf': 97, 'feature_fraction': 0.40456867525463125, 'num_iterations': 109}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:36:09,110] Trial 62 finished with value: 533390000.0 and parameters: {'learning_rate': 0.07815337763717865, 'num_leaves': 18, 'min_data_in_leaf': 71, 'feature_fraction': 0.5090829929693514, 'num_iterations': 1454}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:36:10,413] Trial 63 finished with value: 551072500.0 and parameters: {'learning_rate': 0.08409603444100731, 'num_leaves': 9, 'min_data_in_leaf': 123, 'feature_fraction': 0.4740112726747563, 'num_iterations': 59}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:36:17,550] Trial 64 finished with value: 552612500.0 and parameters: {'learning_rate': 0.06741700760311445, 'num_leaves': 17, 'min_data_in_leaf': 23, 'feature_fraction': 0.5675984759187456, 'num_iterations': 241}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:36:21,811] Trial 65 finished with value: 556655000.0 and parameters: {'learning_rate': 0.0894413917523391, 'num_leaves': 14, 'min_data_in_leaf': 254, 'feature_fraction': 0.44848041661795374, 'num_iterations': 163}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:36:25,312] Trial 66 finished with value: 553877500.0 and parameters: {'learning_rate': 0.10499088559578462, 'num_leaves': 21, 'min_data_in_leaf': 52, 'feature_fraction': 0.5361334372668158, 'num_iterations': 90}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:36:26,499] Trial 67 finished with value: 549257500.0 and parameters: {'learning_rate': 0.05435249599770782, 'num_leaves': 10, 'min_data_in_leaf': 79, 'feature_fraction': 0.7027192940671736, 'num_iterations': 64}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:36:29,579] Trial 68 finished with value: 548020000.0 and parameters: {'learning_rate': 0.0810313679698888, 'num_leaves': 33, 'min_data_in_leaf': 390, 'feature_fraction': 0.6456946505337215, 'num_iterations': 79}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:36:33,629] Trial 69 finished with value: 535672500.0 and parameters: {'learning_rate': 0.2615178230862298, 'num_leaves': 12, 'min_data_in_leaf': 169, 'feature_fraction': 0.4207347022375281, 'num_iterations': 178}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:36:37,749] Trial 70 finished with value: 544225000.0 and parameters: {'learning_rate': 0.11874296328929684, 'num_leaves': 42, 'min_data_in_leaf': 475, 'feature_fraction': 0.39740134443445774, 'num_iterations': 106}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:36:41,687] Trial 71 finished with value: 558772500.0 and parameters: {'learning_rate': 0.06840951778905024, 'num_leaves': 40, 'min_data_in_leaf': 298, 'feature_fraction': 0.4737946118554025, 'num_iterations': 65}. Best is trial 15 with value: 569085000.0.
[I 2026-10-11 18:36:44,776] Trial 72 finished with value: 563970000.0 and parameters: {'learning_rate': 0.09802933426956838, 'num_leaves': 30, 'min_data_in_leaf': 214, 'feature_fraction': 0.49497866521357436, 'num_iterations': 59}. Best is trial 15 with value: 569085000.0.

Mejor ganancia CV: 569085000.0 {'learning_rate': 0.06913650068425481, 'num_leaves': 35, 'min_data_in_leaf': 53, 'feature_fraction': 0.47906319306758594, 'num_iterations': 76}

In [29]:
params_us = {'objective': 'binary', 'boosting_type': 'gbdt', 'feature_pre_filter': False,
             'max_bin': 31, 'verbose': -1,
             **{k: v for k, v in study_us.best_params.items() if k != 'num_iterations'}}
iter_us = study_us.best_params['num_iterations']
print(params_us, '| árboles:', iter_us)

def semillerio_us(df_train, df_pred):
    preds = []
    for seed in mis_semillas:
        r = np.random.default_rng(seed)   # cada semilla sortea OTRO 10% de CONTINUA
        m = (r.random(len(df_train)) < 0.1) | (df_train['clase_ternaria'] != 'CONTINUA')
        d = lgb.Dataset(df_train.loc[m, features], label=df_train.loc[m, 'clase_binaria2'])
        modelo_us = lgb.train({**params_us, 'seed': seed}, d, num_boost_round=iter_us)
        preds.append(modelo_us.predict(df_pred[features]))
    return np.mean(preds, axis=0)

prob_us = semillerio_us(train, test)

{'objective': 'binary', 'boosting_type': 'gbdt', 'feature_pre_filter': False, 'max_bin': 31, 'verbose': -1, 'learning_rate': 0.06913650068425481, 'num_leaves': 35, 'min_data_in_leaf': 53, 'feature_fraction': 0.47906319306758594} | árboles: 76

In [30]:
ensamble_us = (rankdata(prob_semillerio2) + rankdata(prob_us)) / 2

comp = pd.DataFrame({
    'verscla03': curva(prob_semillerio2),
    'undersampling': curva(prob_us),
    'ensamble': curva(ensamble_us),
}, index=cortes) / 1e6
print(comp.round(1))
print(pd.DataFrame({'envios': comp.idxmax(), 'ganancia_M': comp.max().round(1)}))

       verscla03  undersampling  ensamble
4000       287.1          275.0     284.9
4500       310.8          292.0     299.8
5000       317.9          306.9     316.8
5500       324.0          319.6     331.6
6000       336.6          334.4     339.9
6500       346.0          335.0     346.0
7000       348.7          338.8     352.0
7500       358.0          348.2     353.6
8000       364.1          347.6     356.4
8500       371.2          358.0     362.4
9000       370.7          365.2     363.0
9500       375.6          360.2     361.4
10000      381.7          360.8     366.3
10500      383.4          363.6     371.2
11000      392.7          360.8     381.7
11500      399.8          372.4     386.6
12000      398.2          372.9     397.1
12500      399.8          381.2     396.6
13000      409.2          379.5     398.2
13500      408.6          379.0     399.8
14000      408.1          387.2     398.2
14500      412.0          385.6     405.4
15000      411.4          389.4     401.5
15500      402.0          385.6     395.4
16000      394.9          385.0     391.6
16500      391.0          385.6     386.6
17000      389.4          379.5     386.1
17500      387.8          379.0     381.2
18000      379.5          376.2     377.3
18500      373.4          366.8     371.2
19000      366.3          365.2     367.4
               envios  ganancia_M
verscla03       14500       412.0
undersampling   15000       389.4
ensamble        14500       405.4

In [31]:
prob_us_futuro = semillerio_us(test, futuro)   # entrena con junio, predice agosto
ensamble_futuro = (rankdata(prob_futuro) + rankdata(prob_us_futuro)) / 2

k = 14500   # cambialo por el mejor corte del ensamble en la celda 20
orden = np.argsort(ensamble_futuro)[::-1]
elegidos = futuro['numero_de_cliente'].values[orden][:k].astype('int64')
archivo = f'entregas/mi_pipeline_ens_us_k{k}.csv'
pd.Series(elegidos).to_csv(archivo, index=False, header=False)
print(archivo, '->', len(elegidos), 'ids')
print(open(archivo).read()[:60])

entregas/mi_pipeline_ens_us_k14500.csv -> 14500 ids
42425357
44781626
42520550
57157011
31959546
57532582
456968